#Ansible Module Name -- ecs_slb_lb.py
#Test Case : Modify load balancer Internet Spec with all parameters
#Ansible Playbook created by - Abha H
---
- name: Modify load balancer Internet Spec with all parameters
  hosts: localhost
  connection: local
  vars_files:
     - ../../vars/alicloud-creds.yml
     - ../vars/general-parameters.yml
     - ../vars/test-environment.yml
   
  tasks:
   - block: 
      - name: Modify load balancer Internet Spec with all parameters
        ecs_slb_lb:
          access_key: '{{ aliyun_acs_access_key }}'
          secret_key: '{{ aliyun_acs_secret_access_key }}'
          region: '{{ region }}'
          status: '{{ status }}'
          load_balancer_id: '{{ SLBId }}'
          internet_charge_type: '{{ internetChargeTypeBandwidth }}'
          bandwidth: '{{ bandwidth }}'
        register: create_slb_result
      - debug: var=create_slb_result
      - assert:
          that:
            - "create_slb_result.changed ==  True"
          msg: 'Test pass PASSED!!! Server Load Balancer name is set successfully.'
               
     
     rescue:
     
      - assert:  
         that:
            - "create_slb_result.changed ==  false"
         msg: 'EXPECTED - SUCCESS!!! 
               Playbook FAILED due to improper input values
               REASON: {{ create_slb_result }}'
         when: 
            - "create_slb_result.changed ==  false"
             