#Ansible Module Name -- ecs_slb_lb.py
#Test Case : Validating Load Balancer Id Parameter
#Ansible Playbook created by - Abha H
---
- name: Validating invalid bandwidth
  hosts: localhost
  connection: local
  vars_files:
     - ../../vars/alicloud-creds.yml
     - ../vars/general-parameters.yml
     - ../vars/test-environment.yml
   
  tasks:
  # Task 1 - Validating invalid Load Balancer Id
  - block: 
    - name: Validating invalid Load Balancer Id
      ecs_slb_lb:
       access_key: '{{ aliyun_acs_access_key }}'
       secret_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       status: '{{ status }}'
       load_balancer_id: '{{ SLBIdInvalid }}'
       internet_charge_type: '{{ internetChargeTypeBandwidth }}'
       bandwidth: '{{ bandwidth }}'
      register: create_slb_result
    - debug: var=create_slb_result
    rescue:
      - assert:  
         that:
            - "create_slb_result.changed ==  false"
         msg: 'Test pass PASSED !!!
               This is a NEGATIVE playbook !!!
               FAILURE - EXPECTED
               REASON: {{ create_slb_result}}'
         when: 
            - "create_slb_result.changed ==  false"

    
     # Task 2 - Validating blank Load Balancer Id Parameter
  - block: 
    - name: Validating blank Load Balancer Id Parameter
      ecs_slb_lb:
       access_key: '{{ aliyun_acs_access_key }}'
       secret_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       status: '{{ status }}'
       load_balancer_id: 
       internet_charge_type: '{{ internetChargeTypeBandwidth }}'
       bandwidth: '{{ bandwidth }}'
      register: create_slb_result
    - debug: var=create_slb_result
    rescue:
      - assert:  
         that:
            - "create_slb_result.changed ==  false"
         msg: 'Test pass PASSED !!!
               This is a NEGATIVE playbook !!!
               FAILURE - EXPECTED
               REASON: {{ create_slb_result}}'
         when: 
            - "create_slb_result.changed ==  false"

