# Ansible Module Name - ECS_Disk
# Interface : CreateDisk
# Playbook Contains Test-Cases for create disk parameter
# Playbook created by : Sachin J


- name: create disk when disk category is not allowed in the region
  hosts: localhost
  connection: local
  

  vars_files:
  
   - ../vars/test-environment.yml
   - ../vars/general-parameters.yml
   - ../../../vars/alicloud-creds.yml
   
     
          
  tasks:
  
   # Task: 1
  
  - block:

    - name: Scenario - 1 create disk when disk category is not allowed in the region

      ecs_disk:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        disk_name: '{{ diskName }}'
        disk_category: '{{ diskCategoryNotAllowed }}'  # Disk category not allowed in the region
        description: '{{ diskDescription }}'
        size: '{{ size }}'
        status: '{{ diskStatus }}'
        disk_tags: '{{ diskTagsValueNull }}' 

      register: result
    - debug: var=result
   
    rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no

    always:
     - assert:
        that:
           - "'failed' in result"
         #  - "'The specified parameter \"DiskCategory\" is not valid.' in result.msg[0]['Error Message']"

      
   