# Ansible Module Name - ECS_Disk
# Interface : CreateDisk
# Playbook Contains Test-Cases for create disk parameter
# Playbook created by : Sachin J


- name: create disk without disk-category and disk-size parameter
  hosts: localhost
  connection: local
  

  vars_files:
  
   - ../vars/test-environment.yml
   - ../vars/general-parameters.yml
   - ../../../vars/alicloud-creds.yml
       
     
          
  tasks:
  
   # Task: 1
  
  - block:

    - name: Scenario 1 - create disk without disk-category and disk-size parameter

      ecs_disk:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        disk_name: '{{ diskName }}'
        #disk_category: '{{ diskcategoryCloud }}'  
        description: '{{ diskDescription }}'
        #size: '{{ size }}'
        status: '{{ diskStatus }}'
       # disk_tags: '{{ diskTagsValueNull }}' 

      register: result1
    - debug: var=result1

    rescue:
      - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
           
    always:
     - assert:
        that: 
           - "'failed'  in result1" 
           - "'The input parameter either \"SnapshotId\" or \"Size\" should be specified.' in result1.msg[0]['Error Message']" 
    


  