#Ansible Module Name -- rds_acc_mgmt.py
#Test Case : Grant account permissions with account password parameter validation
#Ansible Playbook created by - Abha H
---
- name: Grant account with account password parameter validation
  hosts: localhost
  connection: local
  vars_files:
     - ../../../vars/alicloud-creds.yml
     - ../../vars/test-environment.yml
     - ../../vars/general-parameters.yml
   
  tasks:
   - block :
     - name: Scenario 1 - Grant account permissions with invalid account password parameter
       rds_acc_mgmt:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        command: '{{ commandResetPwd }}'
        db_instance_id: '{{ instanceId }}'
        account_name: '{{ accName }}'
        account_password: sfssd
       register: result_scn1
     - debug: var=result_scn1 

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
   - block :
     - name: Scenario 2 - Grant account permissions without account password parameter
       rds_acc_mgmt:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        command: '{{ commandResetPwd }}'
        db_instance_id: '{{ instanceId }}'
        account_name: '{{ accName }}'
       register: result_scn2
     - debug: var=result_scn2 

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
   - block :
     - name: Scenario 3 - Grant account permissions with blank account password parameter
       rds_acc_mgmt:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        command: '{{ commandResetPwd }}'
        db_instance_id: '{{ instanceId }}'
        account_name: '{{ accName }}'
        account_password: 
       register: result_scn3
     - debug: var=result_scn3

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
   - block :
     - name: Scenario 4 - Grant account permissions with command account password as Account password
       rds_acc_mgmt:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        command: '{{ commandResetPwd }}'
        db_instance_id: '{{ instanceId }}'
        account_name: '{{ accName }}'
        Account_password: Accusr@1234
       register: result_scn4
     - debug: var=result_scn4 

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
     always:
      - assert:  
         that:
            - "'failed' in result_scn1"
            - "'account_password length must be between 6 to 32 characters.' in result_scn1.msg"
            
            - "'failed' in result_scn2"
            - "'account_password is required for resetting instance password' in result_scn2.msg"
            
            - "'failed' in result_scn3"
            - "'account_password is required for resetting instance password' in result_scn3.msg"
            
            - "'failed' in result_scn4"
            - "'unsupported parameter for module: Account_password' in result_scn4.msg"
            
         msg: 'Test pass FAILED !!!'