#Ansible Module Name -- ecs_vpc.net.py
#Test Case : Request Eip Status Param Validation
#Ansible Playbook created by - Abha H
---
- name: Request Eip Status Param Validation
  hosts: localhost
  connection: local
  vars_files: 
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../vars/alicloud-creds.yml
  tasks:
  # Task 1 - Validation of Status param with invalid region
   - block: 
     - name: Scenario 1 -Validation of Status param with invalid region
       ecs_vpc_net: 
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ statusInvalid }}'
        bandwidth: '{{ bandwidth }}'
        internet_charge_type: '{{ internetChargeType }}'
       register: req_eip_result_scn1
     - debug: var=req_eip_result_scn1

     rescue:
        - fail:
           msg: "The fail block is added just to handle exception. This block won't be executed ever."
          when: no
            
   # Task 2 - Validation of Status param as blank
   - block: 
     - name: Scenario 2 - Validation of Status param as blank
       ecs_vpc_net: 
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: 
        bandwidth: '{{ bandwidth }}'
        internet_charge_type: '{{ internetChargeType }}'
       register: req_eip_result_scn2
     - debug: var=req_eip_result_scn2

     rescue:
        - fail:
           msg: "The fail block is added just to handle exception. This block won't be executed ever."
          when: no
                     
   # Task 3 - Validation of status param as Status
   - block: 
     - name: Scenario 3 - Validation of status param as Status
       ecs_vpc_net: 
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        Status: '{{ status }}'
        bandwidth: '{{ bandwidth }}'
        internet_charge_type: '{{ internetChargeType }}'
       register: req_eip_result_scn3
     - debug: var=req_eip_result_scn3

     rescue:
        - fail:
           msg: "The fail block is added just to handle exception. This block won't be executed ever."
          when: no

     always:
      - assert:
         that:
            - "'failed' in req_eip_result_scn1"

            - "'failed' in req_eip_result_scn2"

            - "'failed' in req_eip_result_scn3"

         msg: 'Test pass FAILED !!!'

 
 