#Ansible Module Name -- ecs_vpc.net.py
#Test Case : Request Eip Bandwidth Param Validation
#Ansible Playbook created by - Abha H
---
- name: Request Eip Bandwidth Param Validation
  hosts: localhost
  connection: local
  vars_files: 
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../vars/alicloud-creds.yml
  tasks:
   # Task 1 - Validation of Bandwidth param with invalid bandwidth
   - block: 
     - name: Scenario 1 - Validation of Bandwidth param with invalid bandwidth
       ecs_vpc_net: 
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ status }}'
        bandwidth: '{{ bandwidthInvalid }}'
        internet_charge_type: '{{ internetChargeType }}'
       register: req_eip_result_scn1
     - debug: var=req_eip_result_scn1

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   # Task 2 - Validation of bandwidth param as blank
   - block: 
     - name: Scenario 2 - Validation of bandwidth param as blank
       ecs_vpc_net: 
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: ap-southeast-1
        status: '{{ status }}'
        bandwidth: 
        internet_charge_type: '{{ internetChargeType }}'
       register: req_eip_result_scn2
     - debug: var=req_eip_result_scn2

     rescue:
        - fail:
           msg: "The fail block is added just to handle exception. This block won't be executed ever."
          when: no
                     
   # Task 3 - Validation of bandwidth param as Bandwidth
   - block:
     - name: Scenario 3 -  Validation of bandwidth param with invalid region
       ecs_vpc_net:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ status }}'
        Bandwidth: '{{ bandwidth }}'
        internet_charge_type: '{{ internetChargeType }}'
       register: req_eip_result_scn3
     - debug: var=req_eip_result_scn3

     rescue:
        - fail:
           msg: "The fail block is added just to handle exception. This block won't be executed ever."
          when: no

     always:
      - assert:
         that:
            - "'failed' in req_eip_result_scn1"

            - "'failed' not in req_eip_result_scn2"

            - "'failed' in req_eip_result_scn3"

         msg: 'Test pass FAILED !!!'

  post_tasks:
   - name: Release EIP with all parameters
     ecs_vpc_net:
      acs_access_key: '{{ aliyun_acs_access_key }}'
      acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
      region: ap-southeast-1
      status: '{{ statusAbsent }}'
      bandwidth: '{{ bandwidth }}'
      allocation_id: '{{ req_eip_result_scn2.result["AllocationId"] }}'
     when:
      - "req_eip_result_scn2.changed ==  True"

 