# Ansible Module Name - ECS
# Interface - QueryingInstancestatusPresent
# Test Case : Verify playbook is generating an error when state parameter is provided as statusPresent
# Ansible Playbook created by - Sachin J
---

- name: Verify querying instance interface without state parameter as status
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../../vars/alicloud-creds.yml
    
    
  tasks: 
   - block: 
     - name: Verify querying instance interface without state parameter as statusPresent
       ecs: 
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         zone_id: '{{ zone }}'  
         state: '{{ queryingInstanceStatus }}'
        
       register: result
     - debug: var=result 
          
     rescue:
      - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

     always:
     - assert:
        that:
           - "'failed' not in result"


        msg: 'Test pass FAILED !!!'