#Ansible Module Name -- rds_acc_mgmt.py
#Test Case : Create account with Account password parameter validation
#Ansible Playbook created by - Abha H
---
- name: Create account with account password parameter validation
  hosts: localhost
  connection: local
  vars_files:
     - ../../../vars/alicloud-creds.yml
     - ../../vars/test-environment.yml
     - ../../vars/general-parameters.yml
   
  tasks:
   - block :
     - name: Scenario 1 - Create account with invalid account password parameter
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ command }}'
         db_instance_id: '{{ instanceId }}'
         account_name: '{{ accName }}'
         account_password: '{{ accPwdInvalid }}'
         description: '{{ description }}'
         account_type: '{{ accountType }}'
       register: result_scn1
     - debug: var=result_scn1 

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
   - block :
     - name: Scenario 2 - Create account without account password parameter
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ command }}'
         db_instance_id: '{{ instanceId }}'
         account_name: '{{ accName }}'
         description: '{{ description }}'
         account_type: '{{ accountType }}'
       register: result_scn2
     - debug: var=result_scn2 

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
   - block :
     - name: Scenario 3 - Create account with blank account password parameter
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ command }}' 
         db_instance_id: '{{ instanceId }}'
         account_name: '{{ accName }}' 
         account_password: 
         description: '{{ description }}'
         account_type: '{{ accountType }}'
       register: result_scn3
     - debug: var=result_scn3

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
   - block :
     - name: Scenario 4 - Create account with account password parameter as Account password
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ command }}'
         db_instance_id: '{{ instanceId }}'
         account_name: '{{ accName }}'
         Account_password: '{{ accPwd }}'
         description: '{{ description }}'
         account_type: '{{ accountType }}'
       register: result_scn4
     - debug: var=result_scn4

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
   - block :
     - name: Scenario 5 - Create account with account password parameter having 1 char
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ command }}'
         db_instance_id: '{{ instanceId }}'
         account_name: '{{ accName }}'
         account_password: '{{ accPwdWith1Char }}'
         description: '{{ description }}'
         account_type: '{{ accountType }}'
       register: result_scn5
     - debug: var=result_scn5

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
   - block :
     - name: Scenario 6 - Create account with account password parameter having exact 6 char
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ command }}'
         db_instance_id: '{{ instanceId }}'
         account_name: '{{ accName }}'
         account_password: '{{ accPwdWith6Char }}'
         description: '{{ description }}'
         account_type: '{{ accountType }}'
       register: result_scn6
     - debug: var=result_scn6

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
   - pause :
        seconds: 20
        
   - block :
      - name: Scenario 6.1 - delete account
        rds_acc_mgmt:
          acs_access_key: '{{ aliyun_acs_access_key }}'
          acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
          region: '{{ region }}'
          command: '{{ commandDelete }}'
          db_instance_id: '{{ instanceId }}'
          account_name: '{{ accName }}'  
        register: result_del_scn6
      - debug: var=result_del_scn6

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - pause :
        seconds: 20

   - block :
     - name: Scenario 7 - Create account with account password parameter having exact 32 char
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ command }}'
         db_instance_id: '{{ instanceId }}'
         account_name: '{{ accName }}'
         account_password: '{{ accPwdWith32Char }}'
         description: '{{ description }}'
         account_type: '{{ accountType }}'
       register: result_scn7
     - debug: var=result_scn7

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
   - pause :
        seconds: 20
        
   - block :
      - name: Scenario 7.1 - delete account
        rds_acc_mgmt:
          acs_access_key: '{{ aliyun_acs_access_key }}'
          acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
          region: '{{ region }}'
          command: '{{ commandDelete }}'
          db_instance_id: '{{ instanceId }}'
          account_name: '{{ accName }}'  
        register: result_del_scn7
      - debug: var=result_del_scn7

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - block :
     - name: Scenario 8 - Create account with account password parameter having more than 32 char
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ command }}'
         db_instance_id: '{{ instanceId }}'
         account_name: '{{ accName }}'
         account_password: '{{ accPwdWithMoreThan32Char }}'
         description: '{{ description }}'
         account_type: '{{ accountType }}'
       register: result_scn8
     - debug: var=result_scn8     

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
          
     always:
      - assert:  
         that:
            - "'failed' in result_scn1"
            - "'account_password is not valid' in result_scn1.msg"
            
            - "'failed' in result_scn2"
            - "'account_password is required for create account' in result_scn2.msg"
            
            - "'failed' in result_scn3"
            - "'account_password is required for create account' in result_scn3.msg"
            
            - "'failed' in result_scn4"
            - "'unsupported parameter for module: Account_password' in result_scn4.msg"
            
            - "'failed' in result_scn5"
            - "'account_password length must be between 6 to 32 characters.' in result_scn5.msg"

            - "'failed' not in result_scn6"
            - "'failed' not in result_del_scn6"


            - "'failed' not in result_scn7"
            - "'failed' not in result_del_scn7"


            - "'failed' in result_scn8"
            - "'account_password length must be between 6 to 32 characters.' in result_scn8.msg"
            
         msg: 'Test pass FAILED !!!'