#Ansible Module Name -- rds_acc_mgmt.py
#Test Case : Create account with account type parameter validation
#Ansible Playbook created by - Abha H
---
- name: Create account with account type parameter validation
  hosts: localhost
  connection: local
  vars_files:
     - ../../../vars/alicloud-creds.yml
     - ../../vars/test-environment.yml
     - ../../vars/general-parameters.yml
   
  tasks:
   - block :
     - name: Scenario 1 - Create account with invalid account type parameter
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ command }}'
         db_instance_id: '{{ instanceId }}'
         account_name: '{{ accName }}'
         account_password: '{{ accPwd }}'
         description: '{{ description }}'
         account_type: '{{ accountTypeInvalid }}'
       register: result_scn1
     - debug: var=result_scn1 

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
#   - block :
#     - name: Scenario 2 - Create account without account type parameter
#       rds_acc_mgmt:
#         acs_access_key: '{{ aliyun_acs_access_key }}'
#         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
#         region: '{{ region }}'
#         command: '{{ command }}'
#         db_instance_id: '{{ instanceId }}'
#         account_name: '{{ accName }}'
#         account_password: '{{ accPwd }}'
#         description: '{{ description }}'
#       register: result_scn2
#     - debug: var=result_scn2 
#
#     rescue:
#      - fail:
#          msg: "The fail block is added just to handle exception. This block won't be executed ever."
#        when: no
#
#   - pause :
#        seconds: 20
#        
#   - block :
#      - name: Scenario 2.1 - delete account
#        rds_acc_mgmt:
#          acs_access_key: '{{ aliyun_acs_access_key }}'
#          acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
#          region: '{{ region }}'
#          command: '{{ commandDelete }}'
#          db_instance_id: '{{ instanceId }}'
#          account_name: '{{ accName }}'  
#        register: result_del_scn2
#      - debug: var=result_del_scn2
#
#     rescue:
#      - fail:
#          msg: "The fail block is added just to handle exception. This block won't be executed ever."
#        when: no
      
     
   - block :
     - name: Scenario 3 - Create account with blank account type parameter
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ command }}' 
         db_instance_id: '{{ instanceId }}'
         account_name: '{{ accName }}'
         account_password: '{{ accPwd }}'
         description: '{{ description }}'
         account_type: 
       register: result_scn3
     - debug: var=result_scn3

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

#   - pause :
#        seconds: 20
#        
#   - block :
#      - name: Scenario 3.1 - delete account
#        rds_acc_mgmt:
#          acs_access_key: '{{ aliyun_acs_access_key }}'
#          acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
#          region: '{{ region }}'
#          command: '{{ commandDelete }}'
#          db_instance_id: '{{ instanceId }}'
#          account_name: '{{ accName }}'  
#        register: result_del_scn3
#      - debug: var=result_del_scn3
#
#     rescue:
#      - fail:
#          msg: "The fail block is added just to handle exception. This block won't be executed ever."
#        when: no
      
     
   - block :
     - name: Scenario 4 - Create account with account type parameter as Account type
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ command }}'
         db_instance_id: '{{ instanceId }}'
         account_name: '{{ accName }}'
         account_password: '{{ accPwd }}'
         description: '{{ description }}'
         Account_type: '{{ accountType }}'
       register: result_scn4
     - debug: var=result_scn4 

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
     always:
      - assert:  
         that:
            - "'failed' in result_scn1"
            - "'value of account_type must be one of: Normal,normal,Super,super, got: public' in result_scn1.msg"
            
#            - "'failed' not in result_scn2"
#            - "'failed' not in result_del_scn2"

            
            - "'failed' in result_scn3"
            - "'value of account_type must be one of: Normal,normal,Super,super, got: None' in result_scn3.msg"

            
            - "'failed' in result_scn4"
            - "'unsupported parameter for module: Account_type' in result_scn4.msg"
            
         msg: 'Test pass FAILED !!!'