#Ansible Module Name -- ecs_slb.py
#Test Case : Set Backend Server
#Ansible Playbook created by - Sachin J

---
- name: Validating Set Backend Servers LoadBalancerId Parameter
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../vars/alicloud-creds.yml
     
  tasks:
  # Task 1 :
  
  - block:
    - name: Scenario - 1 Set backend servers without providing loadBalancerId
      ecs_slb: 
       acs_access_key: '{{ aliyun_acs_access_key }}'              
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'       
      # region: '{{ region }}'                                 
      #load_balancer_id: '{{ loadBalancerId }}'                 # Without loadBalancerId parameter           
       backend_servers: '{{ backendServers }}'                     
       status: '{{ status }}'
                                            
      register: SetBackendServerResult1
    - debug: var=SetBackendServerResult1
    
    rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
    
   
  - block:
   # Task 2 :
    - name: Scenario - 2 Set backend servers with loadBalancerId parameter which is already deleted
      ecs_slb: 
       acs_access_key: '{{ aliyun_acs_access_key }}'              
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'       
      # region: '{{ region }}'                                 
       load_balancer_id: '{{ loadBalancerIdAlreadyDeleted }}'                     # Already deleted backend server       
       backend_servers: '{{ backendServers }}'                     
       status: '{{ status }}'      
                                      
      register: SetBackendServerResult2
    - debug: var=SetBackendServerResult2
    
    rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
    

    
  - block:
   # Task 3 :
    - name: Scenario - 3 Set backend servers with loadBalancerId parameter which is invalid
      ecs_slb: 
       acs_access_key: '{{ aliyun_acs_access_key }}'              
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'       
     #  region: '{{ region }}'                                 
       load_balancer_id: '{{ loadBalancerIdInvalid }}'                           # Invalid loadBalancerId 
       backend_servers: '{{ backendServers }}'                    
       status: '{{ status }}'      
                                      
      register: SetBackendServerResult3
    - debug: var=SetBackendServerResult3
    
   
    rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no


    always:
      - assert:
         that:
            - "'failed' in SetBackendServerResult1"
            - "'failed' in SetBackendServerResult2"
            - "'failed' in SetBackendServerResult3"
         msg: 'Test pass FAILED !!!'
    