#Ansible Module Name -- ecs_vpc.net.py
#Test Case : Release Eip Allocation Id Param Validation
#Ansible Playbook created by - Abha H
---
- name: Release Eip Allocation Id Param Validation
  hosts: localhost
  connection: local
  vars_files: 
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../vars/alicloud-creds.yml
  tasks:
  # Task 1 - Validation of Allocation Id param with invalid region
   - block: 
     - name: Validation of Allocation Id param with invalid region
       ecs_vpc_net: 
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ statusAbsent }}'
        bandwidth: '{{ bandwidth }}'
        allocation_id: '{{ allocationIdInvalid }}'
       register: req_eip_result_scn1
     - debug: var=req_eip_result_scn1
     rescue:
        - fail:
           msg: "The fail block is added just to handle exception. This block won't be executed ever."
          when: no
            
   # Task 2 - Validation of Allocation Id param as blank
   - block: 
     - name: Validation of Allocation Id param as blank
       ecs_vpc_net: 
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ statusAbsent }}'
        bandwidth: '{{ bandwidth }}' 
        allocation_id: 
       register: req_eip_result_scn2
     - debug: var=req_eip_result_scn2
     rescue:
        - fail:
           msg: "The fail block is added just to handle exception. This block won't be executed ever."
          when: no
                     
   # Task 3 - Validation of allocation_id param as Allocation_id
   - block: 
     - name: Validation of allocation_id param as Allocation_id
       ecs_vpc_net: 
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        Region: '{{ region }}'
        status: '{{ statusAbsent }}'
        bandwidth: '{{ bandwidth }}'
        Allocation_id: '{{ allocationId }}'
       register: req_eip_result_scn3
     - debug: var=req_eip_result_scn3
     rescue:
        - fail:
           msg: "The fail block is added just to handle exception. This block won't be executed ever."
          when: no

     always:
      - assert:
         that:
            - "'failed' in req_eip_result_scn1"

            - "'failed' in req_eip_result_scn2"

            - "'failed' in req_eip_result_scn3"

         msg: 'Test pass FAILED !!!'
 