#Ansible Module Name -- ecs_vpc.net.py
#Test Case : Release Eip Region Param Validation
#Ansible Playbook created by - Abha H
---
- name: Release Eip Region Param Validation
  hosts: localhost
  connection: local
  vars_files: 
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../vars/alicloud-creds.yml
  tasks:
  # Task 1 - Validation of Region param with invalid region
   - block: 
     - name: Validation of Region param with invalid region
       ecs_vpc_net: 
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ regionInvalid }}'
        status: '{{ statusAbsent }}'
        bandwidth: '{{ bandwidth }}'
        allocation_id: '{{ allocationId }}'
       register: req_eip
     - debug: var=req_eip
     rescue:
      - assert:  
         that:
            - "req_eip.changed ==  false"
         msg: 'Test pass PASSED !!!
               This is a NEGATIVE playbook !!!
               FAILURE - EXPECTED
               REASON: {{ req_eip}}'
         when: 
            - "req_eip.changed ==  false"
            
   # Task 2 - Validation of Region param as blank
   - block: 
     - name: Validation of Region param with invalid region
       ecs_vpc_net: 
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: 
        status: '{{ statusAbsent }}'
        bandwidth: '{{ bandwidth }}'
        allocation_id: '{{ allocationId }}'
       register: req_eip
     - debug: var=req_eip
     rescue:
      - assert:  
         that:
            - "req_eip.changed ==  false"
         msg: 'Test pass PASSED !!!
               This is a NEGATIVE playbook !!!
               FAILURE - EXPECTED
               REASON: {{ req_eip}}'
         when: 
            - "req_eip.changed ==  false"
                     
   # Task 3 - Validation of region param as Region
   - block: 
     - name: Validation of Region param with invalid region
       ecs_vpc_net: 
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        Region: '{{ region }}'
        status: '{{ statusAbsent }}'
        bandwidth: '{{ bandwidth }}'
        allocation_id: '{{ allocationId }}'
       register: req_eip
     - debug: var=req_eip
     rescue:
      - assert:  
         that:
            - "req_eip.changed ==  false"
         msg: 'Test pass PASSED !!!
               This is a NEGATIVE playbook !!!
               FAILURE - EXPECTED
               REASON: {{ req_eip}}'
         when: 
            - "req_eip.changed ==  false"
 
 