## Ansible Module Name - ECS_Disk
## Interface : DetachDisk
## Playbook Contains Test-Cases for detach disk 
## Playbook created by : Sachin J
#
#
#- name: Detach disk which is in available state
#  hosts: localhost
#  connection: local
#  
#
#  vars_files:
#  
#   - ../vars/test-environment.yml
#   - ../vars/general-parameters.yml
#   - ../../../vars/alicloud-creds.yml
#     
#     
#          
#  tasks:
#  
#   # Task: 1
#  
#  - block:
#
#    - name: Scenario 1 - Detach disk which is in availabe state
#
#      ecs_disk:
#        acs_access_key: '{{ aliyun_acs_access_key }}'
#        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
#        region: '{{ region }}'
#        disk_id: '{{ diskIdInvalid }}'   # Disk is not attached to an instance
#        status: '{{ diskStatus }}'
#       
#      register: result
#    - debug: var=result
#
#    rescue:
#    - debug: msg="Failure Expected - We can not detach the disk which is in availabe state"
#    
#
#
#    
#
#
