## Ansible Module Name - ECS_Disk
## Interface : DetachDisk
## Playbook Contains Test-Cases for detach disk 
## Playbook created by : Sachin J
#
#
#- name: Detach disk when instance_id and disk_id parameter is provided
#  hosts: localhost
#  connection: local
#  
#
#  vars_files:
#  
#   - ../vars/test-environment.yml
#   - ../vars/general-parameters.yml
#   - ../../../vars/alicloud-creds.yml
#       
#     
#          
#  tasks:
#  
#   # Task: 1
#  
#  - block:
#
#    - name: Scenario 1 - Detach disk when instance_id and disk_id parameter is provided
#
#      ecs_disk:
#        acs_access_key: '{{ aliyun_acs_access_key }}'
#        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
#        region: '{{ region }}'   
#        instance_id: '{{ ecsInstanceId }}'      
#        disk_id: '{{ diskId }}'   
#        status: '{{ diskStatus }}' 
#     
#    rescue:
#      - fail:
#         msg: "The fail block is added just to handle exception. This block won't be executed ever."
#        when: no
#      
#    always:
#     - assert:
#        that: 
#           - "'failed' in result1" 
#           


    


