#Ansible Module Name -- ecs_slb_lb.py
#Test Case : Validating Region Parmeter while creating SLB
#Ansible Playbook created by - Abha H
---
- name: Validating Region Parmeter while creating SLB
  hosts: localhost
  connection: local
  vars_files:
     - ../../vars/alicloud-creds.yml
     - ../vars/test-environment.yml
     - ../vars/general-parameters.yml
   
  tasks:
   # Task 1 : Validating Region with numbers
   - block:
     - name: Scenario 1 - Validating Region with numbers
       ecs_slb_lb:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ regionNos }}'
        master_zone_id: '{{ masterZone }}'
        slave_zone_id: '{{ slaveZone }}'
        scheme: '{{ scheme }}'
        internet_charge_type: '{{ internetChargeType }}'
        wait: '{{ wait }}'
        wait_timeout: '{{ waitTimeout }}'
       register: create_slb_result_scn1
     - debug: var=create_slb_result_scn1

     rescue:
        - fail:
            msg: "The fail block is added just to handle exception. This block won't be executed ever."
          when: no

   # Task 2 : Validating Region with Special Characters
   - block:
     - name: Scenario 2 - Validating Region with spl chars
       ecs_slb_lb:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ regionSplChar }}'
        master_zone_id: '{{ masterZone }}'
        slave_zone_id: '{{ slaveZone }}'
        scheme: '{{ scheme }}'
        internet_charge_type: '{{ internetChargeType }}'
        wait: '{{ wait }}'
        wait_timeout: '{{ waitTimeout }}'
       register: create_slb_result_scn2
     - debug: var=create_slb_result_scn2

     rescue:
        - fail:
            msg: "The fail block is added just to handle exception. This block won't be executed ever."
          when: no

   # Task 3 : Validating Region with Alphanumeric value
   - block:
     - name: Scenario 3 - Validating Region with alphanumeric value
       ecs_slb_lb:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ regionAlphaNo }}'
        master_zone_id: '{{ masterZone }}'
        slave_zone_id: '{{ slaveZone }}'
        scheme: '{{ scheme }}'
        internet_charge_type: '{{ internetChargeType }}'
        wait: '{{ wait }}'
        wait_timeout: '{{ waitTimeout }}'
       register: create_slb_result_scn3
     - debug: var=create_slb_result_scn3

     rescue:
        - fail:
            msg: "The fail block is added just to handle exception. This block won't be executed ever."
          when: no

   # Task 4 : Validating Region as blank
   - block:
     - name: Scenario 4 - Validating Region as blank
       ecs_slb_lb:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ regionBlank }}'
        master_zone_id: '{{ masterZone }}'
        slave_zone_id: '{{ slaveZone }}'
        scheme: '{{ scheme }}'
        internet_charge_type: '{{ internetChargeType }}'
        wait: '{{ wait }}'
        wait_timeout: '{{ waitTimeout }}'
       register: create_slb_result_scn4
     - debug: var=create_slb_result_scn4

     rescue:
        - fail:
            msg: "The fail block is added just to handle exception. This block won't be executed ever."
          when: no

   # Task 5 : Validating region as Region
   - block:
     - name: Scenario 5 - Validating region as Region
       ecs_slb_lb:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        Region: '{{ region }}'
        master_zone_id: '{{ masterZone }}'
        slave_zone_id: '{{ slaveZone }}'
        scheme: '{{ scheme }}'
        internet_charge_type: '{{ internetChargeType }}'
        wait: '{{ wait }}'
        wait_timeout: '{{ waitTimeout }}'
       register: create_slb_result_scn5
     - debug: var=create_slb_result_scn5

     rescue:
        - fail:
            msg: "The fail block is added just to handle exception. This block won't be executed ever."
          when: no

     always:
      - assert:
         that:
            - "'failed' in create_slb_result_scn1"
            - "'failed' in create_slb_result_scn2"
            - "'failed' in create_slb_result_scn3"
            - "'failed' in create_slb_result_scn4"
            - "'failed' in create_slb_result_scn5"
         msg: 'Test pass FAILED !!!'