#Ansible Module Name -- ecs_slb_lb.py
#Test Case : create server load balancer with Backend Server of different Region
#Ansible Playbook created by - Abha H
---
- name: create server load balancer with Backend Server of different Region
  hosts: localhost
  connection: local
  vars_files:
     - ../../vars/alicloud-creds.yml
     - ../vars/test-environment.yml
     - ../vars/general-parameters.yml
   
  tasks:
   - pause:
       seconds: 20
   - block:
     - name: create server load balancer with Backend Server of different Region
       ecs_slb_lb:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         status: '{{ status }}'
         load_balancer_name: '{{ SLBName }}'
         address_type: '{{ addressType }}'
         vswitch_id: '{{ VSwitchId }}'
         master_zone_id: '{{ masterZone}}'
         slave_zone_id: '{{ slaveZone }}'
         bandwidth: '{{ bandwidth }}'
         listeners: '{{ listeners }}'
         instance_ids: '{{ instanceIdsOfDiffRegion }}'
         internet_charge_type: '{{ internetChargeType }}'
         validate_certs: '{{ validateCerts }}'
         tags: '{{ tags }}'
         wait: '{{ wait }}'
         wait_timeout: '{{ waitTimeout }}'

       register: create_slb_result
     - debug: var=create_slb_result

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

     always:
      - assert:  
         that:
            - "'failed' in create_slb_result"
         msg: 'Test pass FAILED !!!
               FAILURE - EXPECTED
               REASON: {{ create_slb_result }}'

