#Ansible Module Name -- ecs_slb_lb.py
#Test Case : create server load balancer for a single zone region without master zone
#Ansible Playbook created by - Abha H
---
- name: create server load balancer for a single zone region without master zone
  hosts: localhost
  connection: local
  vars_files:

     - ../../vars/alicloud-creds.yml
     - ../vars/test-environment.yml
     - ../vars/general-parameters.yml

  tasks: 
   - block:
     - name: create server load balancer for a single zone region without master zone
       ecs_slb_lb:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         status: '{{ status }}'
         load_balancer_name: '{{ SLBName }}'
         address_type: '{{ addressType }}'
         slave_zone_id: '{{ slaveZone }}'
         bandwidth: '{{ bandwidth }}'
         listeners: '{{ listeners }}'
         internet_charge_type: '{{ internetChargeType }}'
         validate_certs: '{{ validateCerts }}'
         tags: '{{ tags }}'
         wait: '{{ wait }}'
         wait_timeout: '{{ waitTimeout }}'

       register: create_slb_result
     - debug: var=create_slb_result

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

     always:
      - assert:  
         that:
            - "create_slb_result.changed ==  false"
            -  "'provide master_zone_id first' in create_slb_result.msg"
         msg: 'Test pass FAILED !!!
               FAILURE - EXPECTED
               REASON: {{ create_slb_result}}'
         #when:
         #   - "create_slb_result.changed ==  false"