# Ansible Module Name - ECS_GROUP
# Interface : ECS_CreateInstance
# Playbook Contains Test-Cases for password parameter
# Playbook created by : Sachin Jagtap



- name: create instance
  hosts: localhost
  connection: local
  
  vars_files:
  
    - vars/test-environment.yml
    - vars/alicloud-creds.yml   
        
       
  tasks:
  
  # Task : 1
  # It is accepting special symbol as in UTF-8 format
  - block:
    - name: Validating - Valid Password Parameter Which Accepts Special Symbol
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostName }}'
        password: '{{ PasswordSpecialSymbol }}'
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
  
    rescue:
    - debug: msg="Expected - Success "
    
 
  # Task : 2
  
  
  - block:
    - name: Validating - Valid Password Parameter Which Accepts Uppercase, Lowercase, Numerals
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostName }}'
        password: '{{ PasswordValid }}'
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
  
    rescue:
    - debug: msg="Expected - Success"
    
 
  # Task : 3
  
 
  - block:
    - name: Validaing - Invalid Password Parameter Which Accepts More Than 30 characters
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostName }}'
        password: '{{ PasswordMoreThan30Char }}'   # Invalid
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
  
    rescue:
    - debug: msg="Failure Expected - '{{ PasswordMoreThan30Char }}' is not a valid parameter"
  
  
  # Task : 4
  
  
  - block:
    - name: Validating - Valid Password Parameter Which Accepts 30 Characters Only
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostName }}'
        password: '{{ Password30CharOnly }}'   
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
  
    rescue:
    - debug: msg="Expected - Success"
    
  
  # Task : 5
  
  
  - block:
    - name: Validating - Invalid Password Parameter Which Accepts Less Than 8 Characters
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostName }}'
        password: '{{ PasswordLessThan8Char }}'   # Invalid
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
  
    rescue:
    - debug: msg="Failure Expected - '{{ PasswordLessThan8Char }}' is not a valid parameter"
 
 
 # Task : 6
 
 
  - block:
    - name: Validating - Valid Password Parameter Which Accepts 8 Characters Only
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostName }}'
        password: '{{ Password8CharOnly }}'
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
  
    rescue:
    - debug: msg="Expected - Success"
 
 
 # Task : 7
 
 
  - block:
    - name: Validating - Valid Password Parameter Which Accepts Null Characters
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostName }}'
        password: '{{ PasswordNull }}'
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
  
    rescue:
    - debug: msg="Expected Success"
 
 
 # Task : 8
 
 
  - block:
    - name: Validating - Valid Password Parameter Which Accepts Default Characters As Null
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostName }}'
        # password: '{{ Password }}'  Default password
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
  
    rescue:
    - debug: msg="Expected - Success"
  
  
  # Task : 9
  
  
    - block:
    - name: Validating - Invalid Password Parameter Which Accepts Alphabetic characters
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostName }}'
        password: '{{ PasswordAlphabeticCharOnly }}'  # Invalid
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
  
    rescue:
    - debug: msg="Failure Expected - '{{ PasswordAlphabeticCharOnly }}'  is not a valid parameter"