# Ansible Module Name - ECS_GROUP
# Interface : ECS_CreateInstance
# Playbook Contains Test-Cases for RegionId parameter
# Playbook created by : Sachin Jagtap



- name: create instance
  hosts: localhost
  connection: local
 
    
  vars_files:
  
    - vars/test-environment.yml
    - vars/alicloud-creds.yml   
          
     
  tasks:
  
  # Task: 1
  
  - block:
    - name: Validating - Valid RegionId Parameter
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostName }}'
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
  
  
    rescue:
    - debug: msg="Expected - Success"
 
 # Task: 2
 
  - block:
    - name: Validating - Invalid RegionId Parameter
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionInvalid }}'   # Invalid
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostName }}'
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
  
  
    rescue:
    - debug: msg="Failure Expected - '{{ RegionInvalid }}' is not a valid parameter"
 
 # Task: 3
 
  - block:
    - name: Validating - Invalid RegionId Parameter As Null
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionNull }}'    # Null Region
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostName }}'
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
  
  
    rescue:
    - debug: msg="Failure Expected - '{{ RegionNull }}' is not a valid parameter"
  
  # Task: 4
  
  - block:
    - name: Validating - Invalid RegionId Parameter Which Accepts Default Region
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        #region: '{{ RegionValid }}'   Default region
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostName }}'
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
  
  
    rescue:
    - debug: msg="Failure Expected - We can not create an instance without region parameter"