# Ansible Module Name - ECS_GROUP
# Interface : ECS_CreateInstance
# Playbook Contains Test-Cases for HostName parameter
# Playbook created by : Sachin Jagtap

- name: create instance
  hosts: localhost
  connection: local
  
  vars_files:
  
    - vars/test-environment.yml
    - vars/alicloud-creds.yml 
    
  tasks:
  
   # Task : 1
  
  - block:
    - name: Validating - Valid Host Name As Null Parameter
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostNameNull }}'
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
        
      register: result
    - debug: var=result
        
    rescue:
    - debug: msg="Expected - Success"
 
 # Task : 2
 
  - block:
    - name: Validating - Invalid HostName Parameter Which Accepts Other Special Characters
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostNameOtherSpecialChar }}'  # Invalid
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
    
    rescue:
    - debug: msg=" Failure Expected - '{{ HostNameOtherSpecialChar }}' is not a valid parameter"
 
 # Task : 3
 
  - block:
    - name: Validating - Valid HostName Parameter Which Accepts Special Characters
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostNameSpecialChar }}'
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
    
    rescue:
    - debug: msg="Expected - Success"
  
  # Task : 4
  
  - block:
    - name: Validating - Valid HostName Parameter Which Accepts Default Characters
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        #host_name: '{{ HostName }}'   Default characters
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
    
    rescue:
    - debug: msg=" Expected - Success"
 
 # Task : 5
 
  - block:
    - name: Validating - Valid HostName Parameter Which Accepts AlphaNumeric Characters
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostNameAlphanumeric }}'
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
    
    rescue:
    - debug: msg="Expected - Success"
  
  # Task : 6
  
  - block:
    - name: Validating - Valid HostName Parameter Which Accepts Valid Characters
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostNameValid }}'
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
    
    rescue:
    - debug: msg="Expected - Success"
  
  # Task : 7
  
  - block:
    - name: Validating - Invalid HostName Parameter Which Accepts Less Than 2 Characters
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostNameLessThan2Chars }}'   # Invalid
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
    
    rescue:
    - debug: msg=" Failure Expected - '{{ HostNameLessThan2Chars }}' is not a valid parameter"
 
 # Task : 8
 
  - block:
    - name: Validating - Invalid HostName Parameter Which Accepts More Than 128 Characters
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostNameMoreThan128Chars }}'    # Invalid
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
    
    rescue:
    - debug: msg=" Failure Expected - '{{ HostNameMoreThan128Chars }}' is not a valid parameter"
 
 # Task : 9
 
  - block:
    - name: Validating - Valid HostName Parameter Which Accepts 128 Characters Only
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostName128CharOnly }}'
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
    
    rescue:
    - debug: msg=" Expected - Success"

# Task : 10

  - block:
    - name: Validating - Invalid HostName Parameter Which Accepts Dot At The Begining
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostNameWithDotInStarting }}'   # Invalid
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
    
    rescue:
    - debug: msg="Failure Expected - '{{ HostNameWithDotInStarting }}' is not a valid parameter"
 
 # Task : 11
 
  - block:
    - name: Validating - Invalid HostName Parameter Which Accepts 2 Consecutive Dot
      ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostNameWith2Dot }}'    # Invalid
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
      register: result
    - debug: var=result
    
    rescue:
    - debug: msg=" Failure Expected - '{{ HostNameWith2Dot }}' is not a valid parameter "