# Ansible Module Name - ECS_GROUP
# Interface : ECS_CreateInstance
# Playbook Contains Test-Cases for AccessKey and SecretKey Parameters
# Playbook created by : Sachin Jagtap



- name: Validating Access key and Secret key
  hosts: localhost
  connection: local



  vars_files:
    - vars/test-environment.yml
    - vars/alicloud-creds.yml
    
  tasks:
  
  # Task : 1
  
   - block:  
     - name: Validating - Valid AccessKey and Valid SecretKey parameter 
       ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostName }}'
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
       register: result
     - debug: var=result
     
     rescue: 
     - debug: msg="Expected - Success"  
 
  # Task : 2
 
   - block:  
     - name: Validating - Valid AccessKey and Invalid SecretKey parameter (Invalid Test - Case)
       ecs:
        acs_access_key_id: '{{ Shuwei_acs_access_key_id }}'
        acs_secret_access_key: '{{ Invalid_acs_secret_access_key }}'  # Invalid 
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostName }}'
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
       register: result
     - debug: var=result
     
     rescue: 
     - debug: msg="Failure Expected - '{{ Invalid_acs_secret_access_key }}' is not a valid parameter" 
  
  # Task : 3
  
   - block:  
     - name: Validating - Invalid AccessKey and Valid SecretKey parameter (Invalid Test - Case)
       ecs:
        acs_access_key_id: '{{ Invalid_acs_access_key_id }}'    # Invalid 
        acs_secret_access_key: '{{ Shuwei_acs_secret_access_key }}'
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostName }}'
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
       register: result
     - debug: var=result
     
     rescue: 
     - debug: msg="Failed Expected - '{{ Invalid_acs_access_key_id }}' is not a valid parameter"   
 
 # Task : 4
 
   - block:  
     - name: Validating - Invalid AccessKey and Invalid SecretKey parameter (Invalid Test - Case)
       ecs:
        acs_access_key_id: '{{ Invalid_acs_access_key_id }}'           # Invalid 
        acs_secret_access_key: '{{ Invalid_acs_secret_access_key }}'   # Invalid 
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostName }}'
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
       register: result
     - debug: var=result
     
     rescue: 
     - debug: msg="Failure Expected - '{{ acs_access_key_invalid }}' , '{{ acs_secret_access_key_invalid }}' are not valid key parameters"    
 
 # Task : 5
 
   - block:  
     - name: Validating - Instance Is Created Without Accesskey, Secretkey (Invalid Test - Case)
       ecs:
       
       # Access key , Secret key are not given.
        region: '{{ RegionValid }}'
        zone_id: '{{ ZoneValid }}'
        image_id: '{{ ImageIdValid }}'
        instance_type: '{{ InstanceType }}'
        instance_name: '{{ InstanceName }}'
        description: '{{ Description }}'
        host_name: '{{ HostName }}'
        password: '{{ Password }}'
        state: '{{ StateValid }}'
        
       register: result
     - debug: var=result
     
     rescue: 
      - debug: msg="Failure Expected - We can not create an instance without Accesskey and Secretkey."     
     
    
 
  
