#Ansible Module Name -- ecs_slb_lb.py
#Test Case : Validating Load Balancer Id
#Ansible Playbook created by - Abha H
---
- name: Validating Load Balancer Id
  hosts: localhost
  connection: local
  vars_files:
     - ../../vars/alicloud-creds.yml
     - ../vars/general-parameters.yml
     - ../vars/test-environment.yml
   
  tasks:
  # Task 1 - Validating Load Balancer Id
   - block: 
     - name: Validating Load Balancer Id
       ecs_slb_lb:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ statusAbsent }}'
        load_balancer_id: '{{ SLBIdInvalid }}'
       register: delete_slb_result_task1
     - debug: var=delete_slb_result_task1
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
    
    # Task 2 - Validating Load Balancer Id
   - block: 
     - name: Validating Load Balancer Id
       ecs_slb_lb:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ statusAbsent }}'
        load_balancer_id: 
       register: delete_slb_result_task2
     - debug: var=delete_slb_result_task2
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

     always:
      - assert:  
         that:
            - "delete_slb_result_task1.changed ==  false"
         
            - "delete_slb_result_task2.changed ==  false"
            - "'Load Balancer ID is required to delete load balancer' in delete_slb_result_task2.msg"
            
         msg: 'Test pass FAILED !!!'