#Ansible Module Name -- oss.py
#Test Case : Create folder with all parameters
#Ansible Playbook created by - Abha H
---
- name: Create folder with all parameters
  hosts: localhost
  connection: local
  vars_files:
     - ../../../vars/alicloud-creds.yml
     - ../../vars/test-environment.yml
     - ../../vars/general-parameters.yml
   
  tasks:
   - block:
     - name: Scenario 1 - Create folder with all parameters
       oss:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         mode: '{{ modePutFolder }}'
         bucket: '{{ bucketForFolder }}'
         folder_name: '{{ folderName }}'
         region: '{{ region }}'
       register: result_scn1
     - debug: var=result_scn1
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - block:
     - name: Scenario 2 - Create folder with duplicate name
       oss:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         mode: '{{ modePutFolder }}'
         bucket: '{{ bucketForFolder }}'
         folder_name: '{{ folderName }}'
         region: '{{ region }}'
       register: result_scn2
     - debug: var=result_scn2
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

     always:
      - assert:  
         that:
            - "result_scn1.changed == true"
            - "result_scn2.changed == false"
            - "'Folder already exists' in result_scn2.msg"
         msg: 'Test pass FAILED !!!'
