# Ansible Module Name - ECS_AMI
# Interface : CreateCustomImage
# Playbook Contains Test-Case for creating a custom image
# Playbook created by : Sachin J



- name: Create user defined image without tag key and with tag value
  hosts: localhost
  connection: local
  
  vars_files:
  
    - ../vars/general-parameters.yml
    - ../vars/test-environment.yml
    - ../../../vars/alicloud-creds.yml
      
  tasks:
  
  - block:
  
    - name: Create user defined image without tag key and with tag value
    
      ecs_ami:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        instance_id: '{{ ecsInstanceId }}'   
        image_name: '{{ imageName }}'   
        image_version: '{{ imageVersion }}'
        description: '{{ description}}'
        images_tags: '{{ imagedTagsInvalid }}'  # tag key must be present when tag value is present

      register: result
    - debug: var=result

    rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

    always:
      - assert:
          that:
            - "'failed' in result"
            -  "'tag_key must be present when tag_value is present' in result.msg"
          msg: 'Test pass FAILED!!! Failure Expected - We can not create a custom image without tag key and with tag value parameter.
                REASON: {{ result }}'