#Ansible Module Name -- rds_acc_mgmt.py
#Test Case : Grant account permissions with Account Priviledge parameter validation
#Ansible Playbook created by - Abha H
---
- name: Grant account permissions with account Priviledge parameter validation
  hosts: localhost
  connection: local
  vars_files:
     - ../../../vars/alicloud-creds.yml
     - ../../vars/test-environment.yml
     - ../../vars/general-parameters.yml
   
  tasks:
   - block :
     - name: Scenario 1 - Grant account permissions with invalid account Priviledge parameter
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ commandGrant }}'
         db_instance_id: '{{ instanceId }}'
         account_name: '{{ accName }}'
         db_name: '{{ dbName }}' 
         account_privilege: '{{ accountPriveledgeInvalid }}'
       register: result_scn1
     - debug: var=result_scn1 

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
   - block :
     - name: Scenario 2 - Grant account permissions without account Priviledge parameter
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ commandGrant }}'
         db_instance_id: '{{ instanceId }}'
         account_name: '{{ accName }}'
         db_name: '{{ dbName }}' 
       register: result_scn2
     - debug: var=result_scn2 

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
   - block :
     - name: Scenario 3 - Grant account permissions with blank account Priviledge parameter
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ commandGrant }}'
         db_instance_id: '{{ instanceId }}'
         account_name: '{{ accName }}'
         db_name: '{{ dbName }}' 
         account_privilege: 
       register: result_scn3
     - debug: var=result_scn3

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
   - block :
     - name: Scenario 4 - Grant account permissions with account Priviledge parameter as Account Priviledge
       rds_acc_mgmt:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ commandGrant }}'
         db_instance_id: '{{ instanceId }}'
         account_name: '{{ accName }}'
         db_name: '{{ dbName }}' 
         Account_privilege: '{{ accountPriveledgeGrant }}'
       register: result_scn4
     - debug: var=result_scn4

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
     always:
      - assert:  
         that:
            - "'failed' in result_scn1"
            - "'value of account_privilege must be one of: ReadOnly,ReadWrite, got: public' in result_scn1.msg"
            
            - "'failed' in result_scn2"
            - "'account_privilege is required for granting account permission' in result_scn2.msg"
            
            - "'failed' in result_scn3"
            - "'value of account_privilege must be one of: ReadOnly,ReadWrite, got: None' in result_scn3.msg"
            
            - "'failed' in result_scn4"
            - "'unsupported parameter for module: Account_privilege' in result_scn4.msg"
            
            
         msg: 'Test pass FAILED !!!'