#Ansible Module Name -- ecs_vpc.net.py
#Test Case : Modify EIP with all parameters
#Ansible Playbook created by - Abha H
---
- name: Modify EIP with all parameters
  hosts: localhost
  connection: local
  vars_files: 
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../vars/alicloud-creds.yml
  tasks:
   - block: 
     - name: Modify EIP with all parameters
       ecs_vpc_net: 
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ status }}'
        bandwidth: '{{ bandwidth }}'
        allocation_id: '{{ allocationId }}'
       register: result
     - debug: var=result

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

     always:
      - assert:
         that:
            - "'failed' not in result"

         msg: 'Test pass FAILED !!!'