#Ansible Module Name -- ecs_slb_vsg.py
#Test Case : Create Vserver Group
#Ansible Playbook created by - Sachin J

---
- name: Validating create vserver group with backend servers serverid parameter validation
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../vars/alicloud-creds.yml
     
  tasks:
  # Task : 1 Create vserver group by providing valid serverid in backend server
   - block:
     - name: Scenario 1 - Create vserver group by providing valid serverid in backend server
       ecs_slb_vsg:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         load_balancer_id: '{{ loadBalancerId }}'
         vserver_group_name: '{{ vserverGroupName }}'
         backend_servers: '{{ backendServerServerId }}'  # serverid valid
         status: '{{ status }}'
        
       register: create_vsg_result_scn1
     - debug: var=create_vsg_result_scn1

     rescue:
        - fail:
           msg: "The fail block is added just to handle exception. This block won't be executed ever."
          when: no
    
    
   - block: 
    # Task : 2 Create vserver group by providing invalid serverid in backend server
     - name: Scenario 2 - Create vserver group by providing invalid serverid in backend server
       ecs_slb_vsg: 
        acs_access_key: '{{ aliyun_acs_access_key }}'            
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'  
        region: '{{ region }}'
        load_balancer_id: '{{ loadBalancerId }}'
        vserver_group_name: '{{ vserverGroupName }}'
        backend_servers: '{{ backendServerServerIdInvalid }}'  # Invalid serverid parameter
        status: '{{ status }}'
        
       register: create_vsg_result_scn2
     - debug: var=create_vsg_result_scn2
    
     rescue:
        - fail:
           msg: "The fail block is added just to handle exception. This block won't be executed ever."
          when: no
    
    
   - block: 
    # Task : 3 Create vserver group without providing serverid in backend server
     - name: Scenario 3 - Create vserver group without providing serverid in backend server
       ecs_slb_vsg: 
        acs_access_key: '{{ aliyun_acs_access_key }}'            
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'  
        region: '{{ region }}'
        load_balancer_id: '{{ loadBalancerId }}'
        vserver_group_name: '{{ vserverGroupName }}'
        backend_servers: '{{ backendServerServerIdWithout }}'  # without providing serverid parameter
        status: '{{ status }}'
        
       register: create_vsg_result_scn3
     - debug: var=create_vsg_result_scn3
    
     rescue:
        - fail:
           msg: "The fail block is added just to handle exception. This block won't be executed ever."
          when: no

     always:
      - assert:
         that:
            - "'failed' not in create_vsg_result_scn1"

            - "'failed' in create_vsg_result_scn2"

            - "'failed' in create_vsg_result_scn3"

         msg: 'Test pass FAILED !!!'


  post_tasks:
   - name: Deleting newly created vserver group
     ecs_slb_vsg:
      acs_access_key: '{{ aliyun_acs_access_key }}'
      acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
      region: '{{ region }}'
      vserver_group_id: '{{ create_vsg_result_scn1.result["VServerGroupId"] }}'
      load_balancer_id: '{{ loadBalancerId }}'
      state: absent
     when:
      - "create_vsg_result_scn1.changed ==  True"

    