#Ansible Module Name -- ecs_vpc.py
#Test Case : Querying Vswitch
#Ansible Playbook created by - Sachin J

---
- name: Validating querying vswitch list 
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../vars/alicloud-creds.yml
     
  tasks:
  # Task 1 :  Querying vswitch list when invalid vpcId is provided
  - block:
    - name: Scenario 1 - Querying vswitch list when invalid vpcId is provided
      ecs_vpc: 
       acs_access_key: '{{ aliyun_acs_access_key }}'                 
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'         
       region: '{{ region }}'
       zone_id: '{{ zone }}'
       vpc_id: '{{ vpcIdInvalid }}'   # Invalid vpcid
       vswitch_id: '{{ vswitchId }}'  
                      
       state: '{{ statusQueryingVswitch }}'                                        
                          
      register: query_vswitch_result_scn1
    - debug: var=query_vswitch_result_scn1

    rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no

  # Task 2 :  Querying vswitch list when invalid vswitchid is provided
  - block:
    - name: Scenario 2 - Querying vswitch list when invalid vswitchid is provided
      ecs_vpc: 
       acs_access_key: '{{ aliyun_acs_access_key }}'                 
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'         
       region: '{{ region }}'
       zone_id: '{{ zone }}'
       vpc_id: '{{ vpcId }}'
       vswitch_id: '{{ vswithIdInvalid }}'    # Invalid vswitch id
                    
       state: '{{ statusQueryingVswitch }}'                                        
                          
      register: query_vswitch_result_scn2
    - debug: var=query_vswitch_result_scn2
    
    rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no
            
  # Task 3 : Querying vswitch list when invalid zoneid is provided
  - block:
    - name: Scenario 3 - Querying vswitch list when invalid zoneid is provided
      ecs_vpc:
       acs_access_key: '{{ aliyun_acs_access_key }}'                 
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'         
       region: '{{ region }}'
       zone_id: '{{ zoneInvalid }}'    # Invalid zone
       vpc_id: '{{ vpcId }}'
       vswitch_id: '{{ vswitchId }}'    
       #pagenumber: '{{ pageNumberString }}'
       #pagesize: '{{ pageSizeString }}'                  
       state: '{{ statusQueryingVswitch }}'                                        
                          
      register: query_vswitch_result_scn3
    - debug: var=query_vswitch_result_scn3
    
    rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no
            
  # Task : 4  Querying vswitch list when pagenumber and pagesize are provided as string
  - block:
    - name: Scenario 4 -  Querying vswitch list when pagenumber and pagesize are provided as string
      ecs_vpc: 
       acs_access_key: '{{ aliyun_acs_access_key }}'                 
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'         
       region: '{{ region }}'
       zone_id: '{{ zone }}'   
       vpc_id: '{{ vpcId }}'
       vswitch_id: '{{ vswitchId }}'    
       pagenumber: '{{ pageNumberString }}'   # PageNumberString
       pagesize: '{{ pageSizeString }}'       # PageSizeString           
       state: '{{ statusQueryingVswitch }}'                                        
                          
      register: query_vswitch_result_scn4
    - debug: var=query_vswitch_result_scn4

    rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no

  # Task 5 :  Querying vswitch list with all valid parameters
  - block:
    - name: Scenario 5 - Querying vswitch list with all valid parameters
      ecs_vpc: 
       acs_access_key: '{{ aliyun_acs_access_key }}'                 
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'         
       region: '{{ region }}'
       zone_id: '{{ zone }}'   
       vpc_id: '{{ vpcId }}'
       vswitch_id: '{{ vswitchId }}'    
      #pagenumber: '{{ pageNumberString }}'  
      #pagesize: '{{ pageSizeString }}'                
       state: '{{ statusQueryingVswitch }}'                                        
                          
      register: query_vswitch_result_scn5
    - debug: var=query_vswitch_result_scn5

    rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no

  # Task : 6  Querying vswitch list from the another region whereas VPC is created in different region
  - block:
    - name: Scenario 6 - Querying vswitch list from the another region whereas VPC is created in different region
      ecs_vpc: 
       acs_access_key: '{{ aliyun_acs_access_key }}'                 
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'         
       region: '{{ regionOther }}'
       zone_id: '{{ zone }}'   
       vpc_id: '{{ vpcId }}'
       vswitch_id: '{{ vswitchId }}'    
      # pagenumber: '{{ pageNumberString }}'   
      # pagesize: '{{ pageSizeString }}'               
       state: '{{ statusQueryingVswitch }}'                                        
                          
      register: query_vswitch_result_scn6
    - debug: var=query_vswitch_result_scn6

    rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no

    # Task : 7 Querying vswitch list with pagenumber parameter more than 50
  - block:
    - name: Scenario 7 - Querying vswitch list with pagenumber parameter more than 50
      ecs_vpc: 
       acs_access_key: '{{ aliyun_acs_access_key }}'                 
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'         
       region: '{{ regionOther }}'
       zone_id: '{{ zone }}'   
       vpc_id: '{{ vpcId }}'
       vswitch_id: '{{ vswitchId }}'    
       pagenumber: '{{ pageNumberMoreThanSize }}'   
      # pagesize: '{{ pageSizeString }}'               
       state: '{{ statusQueryingVswitch }}'

      register: query_vswitch_result_scn7
    - debug: var=query_vswitch_result_scn7

    rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no
            
 # Task : 8 Querying vswitch list without state parameter
  - block:
    - name: Scenario 8 - Querying vswitch list without state parameter
      ecs_vpc: 
       acs_access_key: '{{ aliyun_acs_access_key }}'                 
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'         
       region: '{{ region }}'
       zone_id: '{{ zone }}'   
       vpc_id: '{{ vpcId }}'
       vswitch_id: '{{ vswitchId }}'    
       # pagenumber: '{{ pageNumberMoreThanSize }}'   
       # pagesize: '{{ pageSizeString }}'               
       #state: '{{ statusQueryingVswitch }}'                                        
                          
      register: query_vswitch_result_scn8
    - debug: var=query_vswitch_result_scn8

    rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no

    always:
     - assert:
        that:
           - "'failed' not in query_vswitch_result_scn1"

           - "'failed' not in query_vswitch_result_scn2"

           - "'failed' not in query_vswitch_result_scn3"

           - "'failed' in query_vswitch_result_scn4"

           - "'failed' not in query_vswitch_result_scn5"

           - "'failed' not in query_vswitch_result_scn6"

           - "'failed' not in query_vswitch_result_scn7"

           - "'failed' in query_vswitch_result_scn8"

        msg: 'Test pass FAILED !!!'