#Ansible Module Name - ECS_GROUP
#Test Case : Verify that Playbook is throwing an error when user is trying to create Security Group with invalid region Id
#Ansible Playbook created by - Jogesh N
---
- name: Create Security Group With valid region Id
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml 
    - ../../../vars/alicloud-creds.yml
  
  tasks:
   - block: 
     - name: Scenario - 1  Create Security Group With Invalid region Id
       ecs_group:
        name: '{{ SGName }}' 
       
        # We considered "Security Group Name" as mandatory parameter for ECS_GROUP Module as per FSD where 
        # as API doesnt required "Security Group Name" as Mandatory. 
       
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ regionInvalid }}'
        
       register: result1
     - debug: var=result1
     
     
     rescue:
      - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
    
     
     always:
     - assert:
        that: 
           - "'failed' in result1" 
           - "'Can not find endpoint to access.' in result1.msg[2]" 
          
           