# Ansible Module Name - ECS_Disk
# Interface : AttachDisk
# Playbook Contains Test-Cases for attach disk 
# Playbook created by : Sachin J


- name: Attach disk which is not present in the same region
  hosts: localhost
  connection: local
  

  vars_files:
  
   - ../vars/test-environment.yml
   - ../vars/general-parameters.yml
   - ../../../vars/alicloud-creds.yml
     
          
  tasks:
  
   # Task: 1
  
  - block:
   
    - name: Scenario 1 - Attach disk which is not present in the same region

      ecs_disk:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'    # region and instance is not in the same region
        instance_id: '{{ ecsInstanceId }}'   
        disk_id: '{{ diskOfDifferentRegion }}'               
        device: '{{ deviceName }}'  
        delete_with_instance: '{{ deleteWithInstance }}'
        status: '{{ diskStatus }}'
       

      register: result1
    - debug: var=result1

    rescue:
      - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
     
    always:
     - assert:
        that: 
           - "'failed' in result1" 
           - "'The specified disk does not exist.' in result1.msg[0]['Error Message']" 
           

    




    


