#Ansible Module Name -- rds.py
#Test Case : Create database with all parameters
#Ansible Playbook created by - Abha H
---
- name: Create database with all parameters
  hosts: localhost
  connection: local
  vars_files:
     - ../../../vars/alicloud-creds.yml
     - ../../vars/test-environment.yml
     - ../../vars/general-parameters.yml
   
  tasks:
   - pause :
        seconds: 30  
   - block:
     - name: create database
       rds:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        command: '{{ command }}'
        instance_id: '{{ instanceId }}'
        db_name: '{{ dbName }}'
        db_description: '{{ dbDescription }}'
        character_set_name: '{{ characterSetName }}'
       register: result_scn1
     - debug: var=result_scn1
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - pause:
        seconds: 30

   - block:
     - name: delete database
       rds:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        command: '{{ commandDelete }}'
        instance_id: '{{ instanceId }}'
        db_name: '{{ dbName }}'
       register: result_scn2
     - debug: var=result_scn2
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

     always:
      - assert:  
         that:
            - "'failed' not in result_scn1"
            - "'failed' not in result_scn2"
         msg: 'Test pass FAILED !!!'
               
