#Ansible Module Name -- rds.py
#Test Case : Changing Instance Type with command parameter validation
#Ansible Playbook created by - Abha H
---
- name: Changing Instance Type with command parameter validation
  hosts: localhost
  connection: local
  vars_files:
     - ../../../vars/alicloud-creds.yml
     - ../../vars/test-environment.yml
     - ../../vars/general-parameters.yml
   
  tasks:
   - block:
     - name: Scenario 1 - Changing Instance Type with invalid command parameter
       rds:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ commandInvalid }}'
         instance_id: '{{ instanceId }}'
         db_instance_class: '{{ dbInstanceClass }}'
         db_instance_storage: '{{ dbInstanceStorage }}'
         pay_type: '{{ payType }}'
       register: result_scn1
     - debug: var=result_scn1
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - block:
     - name: Scenario 2 - Changing Instance Type without command parameter
       rds:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         instance_id: '{{ instanceId }}'
         db_instance_class: '{{ dbInstanceClass }}'
         db_instance_storage: '{{ dbInstanceStorage }}'
         pay_type: '{{ payType }}'
       register: result_scn2
     - debug: var=result_scn2
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - block:
     - name: Scenario 3 - Changing Instance Type with blank command parameter
       rds:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: 
         instance_id: '{{ instanceId }}'
         db_instance_class: '{{ dbInstanceClass }}'
         db_instance_storage: '{{ dbInstanceStorage }}'
         pay_type: '{{ payType }}'
       register: result_scn3
     - debug: var=result_scn3
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - block:
     - name: Scenario 4 - Changing Instance Type with command parameter as Command
       rds:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         Command: '{{ commandModify }}'
         instance_id: '{{ instanceId }}'
         db_instance_class: '{{ dbInstanceClass }}'
         db_instance_storage: '{{ dbInstanceStorage }}'
         pay_type: '{{ payType }}'
       register: result_scn4
     - debug: var=result_scn4
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

     always:
      - assert:  
         that:
            - "'failed' in result_scn1"
           # - "'value of command must be one of: create,delete,replicate,grant,revoke,modify,reboot,switch, got: crated' in result_scn1.msg"
            
            - "'failed' in result_scn2"
            
            - "'failed' in result_scn3"
           # - "'value of command must be one of: create,delete,replicate,grant,revoke,modify,reboot,switch, got: None' in result_scn3.msg"
            
            - "'failed' in result_scn4"
            - "'unsupported parameter for module: Command' in result_scn4.msg"
            
         msg: 'Test pass FAILED !!!'
               
