#Ansible Module Name -- rds.py
#Test Case : changing rds instance type with pay type parameter validation
#Ansible Playbook created by - Abha H
---
- name: changing rds instance type with pay type parameter validation
  hosts: localhost
  connection: local
  vars_files:
     - ../../../vars/alicloud-creds.yml
     - ../../vars/test-environment.yml
     - ../../vars/general-parameters.yml
   
  tasks:
   - block:
     - name: Scenario 1 - changing rds instance type with invalid pay type
       rds:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ commandModify }}'
         instance_id: '{{ instanceId }}'
         db_instance_class: '{{ dbInstanceClass }}'
         db_instance_storage: '{{ dbInstanceStorage }}'
         pay_type: '{{ payTypeInvalid }}'
       register: result_scn1
     - debug: var=result_scn1
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
        
        
   - block:
     - name: Scenario 2 - changing rds instance type without pay type
       rds:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ commandModify }}'
         instance_id: '{{ instanceId }}'
         db_instance_class: '{{ dbInstanceClass }}'
         db_instance_storage: '{{ dbInstanceStorage }}'
       register: result_scn2
     - debug: var=result_scn2
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
        
        
   - block:
     - name: Scenario 3 - changing rds instance type with blank pay type
       rds:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ commandModify }}'
         instance_id: '{{ instanceId }}'
         db_instance_class: '{{ dbInstanceClass }}'
         db_instance_storage: '{{ dbInstanceStorage }}'
         pay_type: 
       register: result_scn3
     - debug: var=result_scn3
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
        
        
   - block:
     - name: Scenario 4 - changing rds instance type with pay type as Pay type
       rds:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         region: '{{ region }}'
         command: '{{ commandModify }}'
         instance_id: '{{ instanceId }}'
         db_instance_class: '{{ dbInstanceClass }}'
         db_instance_storage: '{{ dbInstanceStorage }}'
         Pay_type: '{{ payType }}'
       register: result_scn4
     - debug: var=result_scn4
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
        
        
     always:
      - assert:  
         that:
            - "'failed' in result_scn1"
            - "'value of pay_type must be one of: Postpaid,Prepaid, got: Private' in result_scn1.msg"
            
            - "'failed' in result_scn2"
#            - "'region is required' in result_scn2.msg"
            
            - "'failed' in result_scn3"
            - "'value of pay_type must be one of: Postpaid,Prepaid, got: None' in result_scn3.msg"
            
            - "'failed' in result_scn4"
            - "'unsupported parameter for module: Pay_type' in result_scn4.msg"
            
         msg: 'Test pass FAILED !!!'
        