# Ansible Module Name - ECS
# Playbook Contains Test-Cases for Modify Instance With Alias
# Playbook created by : Sachin J


- name: Validating Modify Instance With Alias
  hosts: localhost
  connection: local
 
  vars_files:
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../../vars/alicloud-creds.yml
        
  tasks:
   - block:
   
     # Tasks : 1
     
     - name: Validating Modify Instance With Alias
       ecs:
        ecs_access_key: '{{ aliyun_acs_access_key }}'
        ecs_secret_key: '{{ aliyun_acs_secret_access_key }}'
        ecs_region: '{{ region }}'
        attributes: '{{ descriptionDefaultModify }}'
        state: '{{ state }}'
        
       register: result
     - debug: var=result
     
     rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no

     always:
     - assert:
        that:
           - "'failed' not in result"
      
        msg: 'EXPECTED - SUCCESS!!! 
               Playbook FAILED due to improper input values. 
               REASON: {{ result }}'
      