# Playbook Contains Test-Cases for Modify Instance's Password Parameter
# Playbook created by : Sachin J


- name: modify instance
  hosts: localhost
  connection: local
 
  vars_files: 
  
   - ../vars/test-environment.yml
   - ../vars/general-parameters.yml
   - ../../../vars/alicloud-creds.yml 
   
    
    
    
  tasks:
  
    # Task : 1
    
  - block:
    - name: Scenario 1 - Verifying password field is not accepting less than 6 characters
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        attributes: '{{ passwordLessThan6Modify }}'
        state: '{{ state }}'
        
      register: result_scn1
    - debug: var=result_scn1
    
    rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no
    
     # Task : 2
    
  - block:
    - name: Scenario 2 - Verifying password field is accepting special characters
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        attributes: '{{ passwordSpecialCharModify }}'
        state: '{{ state }}'
        
      register: result_scn2
    - debug: var=result_scn2
    
    rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no
    
     # Task : 3
    
  - block:
    - name: Scenario 3 - Verifying password field is not accepting null characters
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        attributes: '{{ passwordNullCharModify }}'
        state: '{{ state }}'
        
      register: result_scn3
    - debug: var=result_scn3
    
    rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no
    
     # Task : 4
    
  - block:
    - name: Scenario 4 - Verifying password field is accepting alphanumeric characters only
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        attributes: '{{ passwordAlphaNumericModify }}'
        state: '{{ state }}'
        
      register: result_scn4
    - debug: var=result_scn4
    
    rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no
    
     # Task : 5
    
  - block:
    - name: Scenario 5 - Verifying password field is accepting alphabetic characters only
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        attributes: '{{ passwordAlphabeticOnlyModify }}'
        state: '{{ state }}'
        
      register: result_scn5
    - debug: var=result_scn5
    
    rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no
    
     # Task : 6
    
  - block:
    - name: Scenario 6 - Verifying password field is not accepting more than 30 characters
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}' 
        attributes: '{{ passwordMoreThan30Modify }}'
        state: '{{ state }}'
        
      register: result_scn6
    - debug: var=result_scn6
    
    rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no
    
     # Task : 7
    
  - block:
    - name: Scenario 7 - Verifying password field is accepting 30 characters only
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        attributes: '{{ password30CharOnlyModify }}'
        state: '{{ state }}'
        
      register: result_scn7
    - debug: var=result_scn7
    
    rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no
    
     # Task : 8
    
  - block:
    - name: Scenario 8 - Verifying password field is not accepting default characters
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        attributes: '{{   passwordDefaultCharModify }}'
        state: '{{ state }}'
        
      register: result_scn8
    - debug: var=result_scn8
    
    rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no

    always:
     - assert:
        that:
           - "'failed' in result_scn1"

           - "'failed' not in result_scn2"

           - "'failed' in result_scn3"

           - "'failed' not in result_scn4"

           - "'failed' in result_scn5"

           - "'failed' in result_scn6"

           - "'failed' in result_scn7"

           - "'failed' not in result_scn8"
           
        msg: 'EXPECTED - SUCCESS!!! 
              Playbook FAILED due to improper input values. 
              REASON: {{ result_scn8 }}'