#Ansible Module Name -- rds.py
#Test Case : Release Rds instance with all scenarios
#Ansible Playbook created by - Sachin J
---
- name: Release RDS instance with all scenarios
  hosts: localhost
  connection: local
  vars_files:
     - ../../../vars/alicloud-creds.yml
     - ../../vars/test-environment.yml
     - ../../vars/general-parameters.yml
   
  tasks: 
  
  # Task : 1
  - block:
     - name: Scenario 1 - Create an RDS instance
       rds:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        #zone: '{{ zone }}'
        #command: '{{ command }}'
        db_engine: '{{ dbEngineMysql }}'
        engine_version: '{{ engineVersion }}'
        db_instance_storage: '{{ dbInstanceStorage }}'
        db_instance_class: '{{ dbInstanceClass }}'
        instance_net_type: '{{ instanceNetTypeInternet }}'
        security_ip_list: '{{ securityIpList }}'
        pay_type: '{{ payType }}'
        
        
       register: result_scn1
     - debug: var=result_scn1
     
    rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

  - pause:  
      minutes: 3
         
  # Task : 2   
     
  - block: 
     - name: Scenario 2 - Release the created RDS instance without command parameter
       rds:
         ecs_access_key: '{{ aliyun_acs_access_key }}'
         ecs_secret_key: '{{ aliyun_acs_secret_access_key }}'
        # command: '{{ commandDelete }}'
         instance_id: '{{ instanceIdToDelete }}'
         region: '{{ region }}'
         
       register: result_scn2
     - debug: var=result_scn2
     
    rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
        
  - pause:  
      seconds: 30   
        
  # Task : 3      
  - block: 
     - name: Scenario 3 - Release the created RDS instance without instance id parameter
       rds:
         access_key: '{{ aliyun_acs_access_key }}'
         secret_key: '{{ aliyun_acs_secret_access_key }}'
         command: '{{ commandDelete }}'
         #instance_id: '{{ instanceIdToDelete }}'
         region: '{{ region }}'
         
       register: result_scn3
     - debug: var=result_scn3
     
    rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
        
  - pause:  
      seconds: 30      
        
  # Task : 4  
       
  - block: 
     - name: Scenario 4 - Release the created RDS instance with invalid command parameter
       rds:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         command: '{{ commandInvalid }}'  # Invalid command parameter
         instance_id: '{{ instanceIdToDelete }}'
         region: '{{ region }}'
         
       register: result_scn4
     - debug: var=result_scn4
     
    rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
        
  - pause:  
      seconds: 30     
        
    # Task : 5  
       
  - block: 
     - name: Scenario 5 - Release the created RDS instance with invalid instance id parameter
       rds:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         command: '{{ commandDelete }}'  
         instance_id: '{{ instanceIdToDeleteInvalid }}' # Invalid InstanceId parameter
         ecs_region: '{{ region }}'
         
       register: result_scn5
     - debug: var=result_scn5
     
    rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no
        
  - pause:  
      seconds: 30    
       
    # Task : 6  
       
  - block: 
     - name: Scenario 6 - Release the created RDS instance without region parameter
       rds:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         command: '{{ commandDelete }}'  
         instance_id: '{{ instanceIdToDelete }}' 
         #region: '{{ region }}'
         
       register: result_scn6
     - debug: var=result_scn6
     
    rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no  
        
  - pause:  
      seconds: 30
           
    # Task : 7 
       
  - block: 
     - name: Scenario 7 - Release the created RDS instance with invalid region parameter
       rds:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         command: '{{ commandDelete }}'  
         instance_id: '{{ instanceIdToDelete }}' 
         ecs_region: '{{ regionInvalid }}'  # Invalid region
         
       register: result_scn7
     - debug: var=result_scn7
     
    rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no  
             
  - pause:  
      seconds: 30
      
     # Task : 8  
       
  - block: 
     - name: Scenario 8 - Release the created RDS instance
       rds:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         command: '{{ commandDelete }}'  
         instance_id: '{{ result_scn1.result[0].DBInstanceId }}' 
         acs_region: '{{ region }}'
         
       register: result_scn8
     - debug: var=result_scn8
     
    rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no      

    always:
      - assert:  
         that:
            - "'failed' not in result_scn1"                     
            - "'failed' in result_scn2"
            - "'failed' in result_scn3"
            - "'failed' in result_scn4"
            - "'failed' in result_scn5"
            - "'failed' in result_scn6"
            - "'failed' in result_scn7"
            - "'failed' not in result_scn8"
         msg:  'Test pass FAILED !!!'
           


         
  