# Ansible Module Name - ECS
# Interface : CreateInstance
# Playbook Contains Test-Cases for Volume parameter
# Playbook created by : Sachin J



- name: Validatnig volume parameter
  hosts: localhost
  connection: local

  vars_files:
  
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../../vars/alicloud-creds.yml

  tasks:   
  - block: 
    - name: Validating - Volume parameter with invalid volume count  
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
        disks: '{{ invalidDisks }}'                    # Invalid volume count
      register: create_instance_result
    - debug: var=create_instance_result

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
      
  

    always:
    - assert:
        that:
           - "'failed' in create_instance_result"
           - "'more than four volumes or disk are not allowed.' in create_instance_result.msg"
        msg: 'Test pass FAILED !!!'
