
# This playbook is an example for deploying an instances with invalid Insatnt Type

# The play operates on the local (Ansible control) machine.
# Failure Expected
# Ansible playbook created by : Sachin J
---
- name: create an ECS Instance and Add it to the Security Group
  hosts: localhost
  connection: local
  gather_facts: False
  
  vars_files:
  
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../../vars/alicloud-creds.yml
     
  tasks:
   - block:
     - name: create an ECS Linux Instance 
       ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ linuxImageId }}'
        instance_type: '{{ ioOptimizedInvalid }}'
        instance_name: '{{ instanceNameLinux }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
       register: create_instance_result
     - debug: var=create_instance_result

     rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no
       
    

     always:
     - assert:
         that:
            - "'failed' in create_instance_result"
            - "'The specified InstanceType beyond the permitted range.' in create_instance_result.msg[0]['Error Message']"
         msg: 'Test pass FAILED !!!'


