# Ansible Module Name - ECS
# Interface : CreateInstance
# Playbook Contains Test-Cases for ImageId parameter
# Playbook created by : Sachin J

- name: create instance
  hosts: localhost
  connection: local

  vars_files:
  
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../../vars/alicloud-creds.yml

  tasks:
  # Task : 1
  - block:
    - name: Verifying - Invalid ImageID Parameter (Invalid Test-Case)
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ ecsImageIdInvalid }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_1
    - debug: var=create_instance_result_1

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15 
  # Task : 2
  
  - block:
    - name: Verifying - Invalid ImageId Parameter as Null (Invalid Test-Case)
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ imageIdNull }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_2
    - debug: var=create_instance_result_2

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15 
 # Task : 3
 
  - block:
    - name: Verifying - Valid ImageID Parameter (Valid Test-Case)
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_3
    - debug: var=create_instance_result_3

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15 
 # Task : 4
 
  - block:
    - name: Verifying - Instance Is Created With Default ImageId Parameter(Invalid Test-Case)
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        #image_id: '{{ windowsImageId }}'  Without ImageId parameter
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_4
    - debug: var=create_instance_result_4

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no

    always:
     - assert:
         that:
            - "'failed' in create_instance_result_1"
            - "'The specified ImageId does not exist.' in create_instance_result_1.msg[0]['Error Message']"

            - "'failed' in create_instance_result_2"
            - "'image_id is required for new instance' in create_instance_result_2.msg"

            - "'failed' not in create_instance_result_3"

            - "'failed' in create_instance_result_4"
            - "'image_id is required for new instance' in create_instance_result_4.msg"

         msg: 'Test pass FAILED !!!'

  - pause:
        seconds: 15     
   
  post_tasks:
   - name: Deleting newly created instance in Task 3
     ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       instance_id: '{{ create_instance_result_3.result[0].instance_id }}'
       status: absent
     when:
        - "'failed' not in create_instance_result_3"