# Ansible Module Name - ECS
# Interface : CreateInstance
# Playbook Contains Test-Cases for Instance Type parameter
# Playbook created by : Sachin J

- name: create instance
  hosts: localhost
  connection: local

  vars_files:
  
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../../vars/alicloud-creds.yml  

  tasks:
  
  # Task : 1
  
  - block:
    - name: Validating - Invalid instanceType Parameter Which Accepts instanceType As dcs.123.small
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        #instance_type: '{{ instanceTypeInvalid }}'
        type: '{{ instanceTypeInvalid }}'    # Alias
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_1
    - debug: var=create_instance_result_1

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15 
  # Task : 2
  
  - block:
    - name: Validating - Invalid instanceType Parameter Which Accepts instanceType As Null
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceTypeNull }}'
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_2
    - debug: var=create_instance_result_2

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15 
# Task : 3

  - block:
    - name: Validating - Invalid instanceType Parameter Which Accepts instanceType As ecs.n1.small
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceTypeioOptimizedTrue }}'   # ioOptimizedTrue = True
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_3
    - debug: var=create_instance_result_3

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15 
  # Task : 4
  
  - block:
    - name: Validating - Valid instanceTypeParameter Which Accepts instanceType As ecs.t1.small
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceTypeNonioOptimizedTrue }}' # ioOptimizedTrue = false
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_4
    - debug: var=create_instance_result_4

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no

    always:
     - assert:
         that:
            - "'failed' in create_instance_result_1"
            - "'The specified InstanceType beyond the permitted range.' in create_instance_result_1.msg[0]['Error Message']"

            - "'failed' in create_instance_result_2"
            - "'instance_type is required for new instance' in create_instance_result_2.msg"

            - "'failed' not in create_instance_result_3"

            - "'failed' not in create_instance_result_4"
         msg: 'Test pass FAILED !!!'

  - pause:
        seconds: 15     
  
  post_tasks:

    - name: Deleting newly created instance in Task 3
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        instance_id: '{{ create_instance_result_3.result[0].instance_id }}'
        status: absent
      when:
         - "'failed' not in create_instance_result_3"

    - name: Deleting newly created instance in Task 4
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        instance_id: '{{ create_instance_result_4.result[0].instance_id }}'
        status: absent
      when:
         - "'failed' not in create_instance_result_4"

