# Ansible Module Name - ECS
# Interface : CreateInstance
# Playbook Contains Test-Cases for create instance with wait and wait timeout parameter
# Playbook created by : Sachin J



- name: Validating create instance with wait and wait timeout parameter
  hosts: localhost
  connection: local
  
  vars_files:
  
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../../vars/alicloud-creds.yml
      
    
  tasks:
  
  # Task 1:
  
   - block: 
     - name: Validating - Valid wait and wait-timeout parameter
       ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        allocate_public_ip: '{{ allocatePublicIpFalse }}'
        state: '{{ state }}'
        wait: '{{ waitTrue }}'
        wait_timeout: '{{ waitTimeOutValid }}'
       register: create_instance_result_1
     - debug: var=create_instance_result_1

     rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no
     
   - pause:
        seconds: 15    
     # Task 2:
     
   - block: 
     - name: Validating - Invalid wait as False and wait-timeout parameter
       ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        allocate_public_ip: '{{ allocatePublicIpFalse }}'
        state: '{{ state }}'
        wait: '{{ waitFalse }}'
        wait_timeout: '{{ waitTimeOutValid }}'
       register: create_instance_result_2
     - debug: var=create_instance_result_2

     rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no
   - pause:
        seconds: 15 
  
   # Task 3:
     
   - block: 
     - name: Validating - Invalid Wait and valid wait-timeout parameter
       ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        allocate_public_ip: '{{ allocatePublicIpFalse }}'
        state: '{{ state }}'
        wait: '{{ waitInvalid }}'
        wait_timeout: '{{ waitTimeOutValid }}'
       register: create_instance_result_3
     - debug: var=create_instance_result_3

     rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no
   - pause:
        seconds: 15 
  # Task 4:
     
   - block: 
     - name: Validating - Wait parameter as True and wait timeout parameter as 300
       ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        allocate_public_ip: '{{ allocatePublicIpFalse }}'
        state: '{{ state }}'
        wait: '{{ waitTrue }}'
        wait_timeout: '{{ waitTimeOutMax }}'
       register: create_instance_result_4
     - debug: var=create_instance_result_4

     rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no
   - pause:
        seconds: 15 
   # Task 5:
     
   - block: 
     - name: Validating - Wait parameter as True and wait timeout parameter as 325
       ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        allocate_public_ip: '{{ allocatePublicIpFalse }}'
        state: '{{ state }}'
        wait: '{{ waitTrue }}'
        wait_timeout: '{{ waitTimeOutInvalid }}'
       register: create_instance_result_5
     - debug: var=create_instance_result_5

     rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no
   - pause:
        seconds: 15 
  
  # Task 6:
     
   - block: 
     - name: Validating - Wait and wait timeout parameter as default
       ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        allocate_public_ip: '{{ allocatePublicIpFalse }}'
        state: '{{ state }}'
       register: create_instance_result_6
     - debug: var=create_instance_result_6

     rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no

     always:
     - assert:
         that:
            - "'failed' not in create_instance_result_1"

            - "'failed' not in create_instance_result_2"

            - "'failed' in create_instance_result_3"

            - "'failed' not in create_instance_result_4"

            - "'failed' not in create_instance_result_5"

            - "'failed' not in create_instance_result_6"

         msg: 'Test pass FAILED !!!'

   - pause:
        seconds: 15     
   
  post_tasks:

    - name: Deleting newly created instance in Task 1
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        instance_id: '{{ create_instance_result_1.result[0].instance_id }}'
        status: absent
      when:
         - "'failed' not in create_instance_result_1"

    - name: Deleting newly created instance in Task 2
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        instance_id: '{{ create_instance_result_2.result[0].instance_id }}'
        status: absent
      when:
         - "'failed' not in create_instance_result_2"

    - name: Deleting newly created instance in Task 4
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        instance_id: '{{ create_instance_result_4.result[0].instance_id }}'
        status: absent
      when:
         - "'failed' not in create_instance_result_4"

    - name: Deleting newly created instance in Task 5
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        instance_id: '{{ create_instance_result_5.result[0].instance_id }}'
        status: absent
      when:
         - "'failed' not in create_instance_result_5"

    - name: Deleting newly created instance in Task 6
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        instance_id: '{{ create_instance_result_6.result[0].instance_id }}'
        status: absent
      when:
         - "'failed' not in create_instance_result_6"





