# Ansible Module Name - ECS
# Interface : CreateInstance
# Playbook Contains Test-Cases for AccessKey and SecretKey Parameters
# Playbook created by : Sachin J



- name: Validating Access key and Secret key
  hosts: localhost
  connection: local



  vars_files:
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../../vars/alicloud-creds.yml
    
  tasks:
  
  # Task : 1
  
   - block:  
     - name: Validating - Valid AccessKey and Valid SecretKey parameter 
       ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
        
       register: create_instance_result_1
     - debug: var=create_instance_result_1
     
     rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no 
   - pause:
        seconds: 15  
 
  # Task : 2
 
   - block:  
     - name: Validating - Valid AccessKey and Invalid SecretKey parameter (Invalid Test - Case)
       ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ invalid_acs_secret_access_key }}'  # Invalid 
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
       register: create_instance_result_2
     - debug: var=create_instance_result_2
     
     rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no
       
   - pause:
        seconds: 15     
  
  # Task : 3
  
   - block:  
     - name: Validating - Invalid AccessKey and Valid SecretKey parameter (Invalid Test - Case)
       ecs:
        acs_access_key: '{{ invalidAccessKeyId }}'    # Invalid 
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
       register: create_instance_result_3
     - debug: var=create_instance_result_3

     rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no
       
   - pause:
        seconds: 15    
 
 # Task : 4
 
   - block:  
     - name: Validating - Invalid AccessKey and Invalid SecretKey parameter (Invalid Test - Case)
       ecs:
        acs_access_key: '{{ invalidAccessKeyId }}'           # Invalid 
        acs_secret_access_key: '{{ invalid_acs_secret_access_key }}'   # Invalid 
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
       register: create_instance_result_4
     - debug: var=create_instance_result_4

     rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no
       
   - pause:
        seconds: 15     

 
 # Task : 5
 
   - block:  
     - name: Validating - Instance Is Created Without Accesskey, Secretkey (Invalid Test - Case)
       ecs:
       # Access key , Secret key are not given.
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
       register: create_instance_result_5
     - debug: var=create_instance_result_5

     rescue:
     - fail:
         msg: "The fail block is added just to handle exception. This block won't be executed ever."
       when: no

     always:
     - assert:
         that:
            - "'failed' not in create_instance_result_1"

            - "'failed' in create_instance_result_2"
            - "'The request signature does not conform to Aliyun standards.' in create_instance_result_2.msg[0]['Error Message']"

            - "'failed' in create_instance_result_3"
            - "'Specified access key is not found.' in create_instance_result_3.msg[0]['Error Message']"

            - "'failed' in create_instance_result_4"
            - "'Specified access key is not found.' in create_instance_result_4.msg[0]['Error Message']"

            - "'failed' in create_instance_result_5"
            - "'access key is required' in create_instance_result_5.msg"
         msg: 'Test pass FAILED !!!'
         
   - pause:
        seconds: 15         

  post_tasks:
   - name: Deleting newly created instance
     ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       instance_id: '{{ create_instance_result_1.result[0].instance_id }}'
       status: absent
     when:
        - "'failed' not in create_instance_result_1"

     
    
 
  
