# Ansible Module Name - ECS
# Interface : CreateInstance
# Playbook Contains Test-Cases for ImageId parameter
# Playbook created by : Sachin J

- name: create instance
  hosts: localhost
  connection: local

  vars_files:
  
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../../vars/alicloud-creds.yml

  tasks:
 # Task :1
  
  - block:  
    - name: Verifying - Valid instanceName Parameter
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceNameValid }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_1
    - debug: var=create_instance_result_1

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15 
  # Task :2
  
  - block:  
    - name: Validating - Invalid instanceName Parameter As http:// At Begining
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceNameUrl }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_2
    - debug: var=create_instance_result_2

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
    
  - pause:
        seconds: 15 
 # Task :3
 
  - block:
    - name: Validating - Valid instanceName Parameter As AlphaNumeric
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceNameAlphanumeric }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_3
    - debug: var=create_instance_result_3

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15     
 # Task :4 
 
  - block:              
    - name: Validating - Valid instanceName Parameter Which Accepts Special Characters As . - _ only
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceNameSpecialChar }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_4
    - debug: var=create_instance_result_4

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15 
 # Task :5
 
  - block:              
    - name: Validating - Invalid instanceName Parameter Which Accepts Other Special Characters
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceNameOtherSpecialChar }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_5
    - debug: var=create_instance_result_5

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15 
 
 # Task :6
 
  - block:  
    - name: Validating - Valid instanceName Parameter As Null
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceNameNull }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_6
    - debug: var=create_instance_result_6

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15 
 # Task :7       
 
  - block:  
    - name: Validating - Valid instanceName Parameter With Default Which Takes InstanceId Of The Instance
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        # instance_name: '{{ instanceName }}'  Default Instance Name
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_7
    - debug: var=create_instance_result_7

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15 
 # Task :8
 
  - block:   
    - name: Validating - Invalid instanceName Parameter Which Accepts Less Than 2 Characters
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceNameLessThan2Char }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_8
    - debug: var=create_instance_result_8

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15 
 # Task :9
 
  - block:   
    - name: Validating - Invalid instanceName Parameter Which Accepts More Than 128 Characters
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceNameMoreThan128Char }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_9
    - debug: var=create_instance_result_9

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15      
 # Task :10
 
  - block:   
    - name: Validating - Valid instanceName Parameter Which Accepts 128 Characters Only
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName128CharOnly }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_10
    - debug: var=create_instance_result_10

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no

    always:
     - assert:
         that:
            - "'failed' not in create_instance_result_1"

            - "'failed' in create_instance_result_2"
            - "'The specified parameter \"InstanceName\" is not valid.' in create_instance_result_2.msg[0]['Error Message']"

            - "'failed' not in create_instance_result_3"

            - "'failed' not in create_instance_result_4"

            - "'failed' in create_instance_result_5"
            - "'The specified parameter \"InstanceName\" is not valid.' in create_instance_result_5.msg[0]['Error Message']"

            - "'failed' not in create_instance_result_6"

            - "'failed' not in create_instance_result_7"

            - "'failed' in create_instance_result_8"
            - "'The specified parameter \"InstanceName\" is not valid.' in create_instance_result_8.msg[0]['Error Message']"

            - "'failed' in create_instance_result_9"
            - "'The specified parameter \"InstanceName\" is not valid.' in create_instance_result_9.msg[0]['Error Message']"

            - "'failed' not in create_instance_result_10"

         msg: 'Test pass FAILED !!!'

  - pause:
        seconds: 15     
  
  post_tasks:

   - name: Deleting newly created instance in Task 1
     ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       instance_id: '{{ create_instance_result_1.result[0].instance_id }}'
       status: absent
     when:
        - "'failed' not in create_instance_result_1"

   - name: Deleting newly created instance in Task 3
     ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       instance_id: '{{ create_instance_result_3.result[0].instance_id }}'
       status: absent
     when:
        - "'failed' not in create_instance_result_3"

   - name: Deleting newly created instance in Task 4
     ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       instance_id: '{{ create_instance_result_4.result[0].instance_id }}'
       status: absent
     when:
        - "'failed' not in create_instance_result_4"

   - name: Deleting newly created instance in Task 6
     ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       instance_id: '{{ create_instance_result_6.result[0].instance_id }}'
       status: absent
     when:
        - "'failed' not in create_instance_result_6"

   - name: Deleting newly created instance in Task 7
     ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       instance_id: '{{ create_instance_result_7.result[0].instance_id }}'
       status: absent
     when:
        - "'failed' not in create_instance_result_7"

   - name: Deleting newly created instance in Task 10
     ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       instance_id: '{{ create_instance_result_10.result[0].instance_id }}'
       status: absent
     when:
        - "'failed' not in create_instance_result_10"

      
      
      
      
      
      
      
      