# Ansible Module Name - ECS
# Interface : CreateInstance
# Playbook Contains Test-Cases for RegionId parameter
# Playbook created by : Sachin J

- name: create instance
  hosts: localhost
  connection: local

  vars_files:
  
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../../vars/alicloud-creds.yml 

  tasks:
  
  # Task: 1
  
  - block:
    - name: Validating - Valid RegionId Parameter
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_1
    - debug: var=create_instance_result_1

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15 
 # Task: 2
 
  - block:
    - name: Validating - Invalid RegionId Parameter
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ regionInvalid }}'   # Invalid
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_2
    - debug: var=create_instance_result_2

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15 
 # Task: 3
 
  - block:
    - name: Validating - Invalid RegionId Parameter As Null
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ regionNull }}'    # Null Region
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_3
    - debug: var=create_instance_result_3

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15 
  # Task: 4
  
  - block:
    - name: Validating - Invalid RegionId Parameter Which Accepts Default Region
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        #region: '{{ region }}'   Default region
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        state: '{{ state }}'
      register: create_instance_result_4
    - debug: var=create_instance_result_4

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no

    always:
     - assert:
         that:
            - "'failed' not in create_instance_result_1"

            - "'failed' in create_instance_result_2"

            - "'failed' in create_instance_result_3"

            - "'failed' in create_instance_result_4"

         msg: 'Test pass FAILED !!!'

  - pause:
      seconds: 15     

  post_tasks:

    - name: Deleting newly created instance in Task 1
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        instance_id: '{{ create_instance_result_1.result[0].instance_id }}'
        status: absent
      when:
         - "'failed' not in create_instance_result_1"

