# Ansible Module Name - ECS
# Interface : CreateInstance
# Playbook Contains Test-Cases for Allocate Public Ip parameter
# Playbook created by : Sachin J

- name: Validating allocate public ip parameter
  hosts: localhost
  connection: local
  
  vars_files:
  
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../../vars/alicloud-creds.yml
    
  
  tasks:

  # Task : 1

  - block: 
    - name: Validating - Valid AllocatePublicIp Parameter As True
      ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       zone: '{{ zone }}'
       image_id: '{{ windowsImageId }}'
       instance_type: '{{ instanceType }}'
       instance_name: '{{ instanceName }}'
       description: '{{ description }}'
       host_name: '{{ host_name }}'
       password: '{{ password }}'
       allocate_public_ip: '{{ allocatePublicIp }}'
       state: '{{ state }}'
      register: create_instance_result_1
    - debug: var=create_instance_result_1

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
      
  - pause:
        seconds: 15    

    # Task : 2
  
  - block: 
    - name: Validating - Valid AllocatePublicIp Parameter As False
      ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       zone: '{{ zone }}'
       image_id: '{{ windowsImageId }}'
       instance_type: '{{ instanceType }}'
       instance_name: '{{ instanceName }}'
       description: '{{ description }}'
       host_name: '{{ host_name }}'
       password: '{{ password }}'
       allocate_public_ip: '{{ allocatePublicIpFalse }}'
       state: '{{ state }}'
      register: create_instance_result_2
    - debug: var=create_instance_result_2

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15    
 
   # Task : 3
 
  - block: 
    - name: Validating - Valid AllocatePublicIp Parameter As Null
      ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       zone: '{{ zone }}'
       image_id: '{{ windowsImageId }}'
       instance_type: '{{ instanceType }}'
       instance_name: '{{ instanceName }}'
       description: '{{ description }}'
       host_name: '{{ host_name }}'
       password: '{{ password }}'
       allocate_public_ip: '{{ allocatePublicIpNull }}'
       state: '{{ state }}'
      register: create_instance_result_3
    - debug: var=create_instance_result_3

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
      
  - pause:
        seconds: 15     

   # Task : 4
 
  - block: 
    - name: Validating - Invalid AllocatePublicIp Parameter As Yes
      ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       zone: '{{ zone }}'
       image_id: '{{ windowsImageId }}'
       instance_type: '{{ instanceType }}'
       instance_name: '{{ instanceName }}'
       description: '{{ description }}'
       host_name: '{{ host_name }}'
       password: '{{ password }}'
       allocate_public_ip: '{{ allocatePublicIpInvalid }}'
       state: '{{ state }}'
      register: create_instance_result_4
    - debug: var=create_instance_result_4

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
  - pause:
        seconds: 15 
   # Task : 5
   # By default allocate public ip parameter sets true
  - block: 
    - name: Validating - Instance Is Created Without AllocatePublicIp Parameter (Valid Test - Case)
      ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       zone: '{{ zone }}'
       image_id: '{{ windowsImageId }}'
       instance_type: '{{ instanceType }}'
       instance_name: '{{ instanceName }}'
       description: '{{ description }}'
       host_name: '{{ host_name }}'
       password: '{{ password }}'
      # allocate_public_ip: '{{ allocatePublicIp }}'
       state: '{{ state }}'
      register: create_instance_result_5
    - debug: var=create_instance_result_5

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
      
     

    always:
    - assert:
        that:
           - "'failed' not in create_instance_result_1"
           - "'failed' not in create_instance_result_2"
           - "'failed' not in create_instance_result_3"
           - "'failed' not in create_instance_result_4"
           - "'failed' not in create_instance_result_5"
        msg: 'Test pass FAILED !!!'
  - pause:
        seconds: 15   

  post_tasks:

   - name: Deleting newly created instance in Task 1
     ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       instance_id: '{{ create_instance_result_1.result[0].instance_id }}'
       status: absent
     when:
        - "'failed' not in create_instance_result_1"

   - name: Deleting newly created instance Task 2
     ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       instance_id: '{{ create_instance_result_2.result[0].instance_id }}'
       status: absent
     when:
        - "'failed' not in create_instance_result_2"

   - name: Deleting newly created instance Task 3
     ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       instance_id: '{{ create_instance_result_3.result[0].instance_id }}'
       status: absent
     when:
        - "'failed' not in create_instance_result_3"

   - name: Deleting newly created instance Task 4
     ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       instance_id: '{{ create_instance_result_4.result[0].instance_id }}'
       status: absent
     when:
        - "'failed' not in create_instance_result_4"

   - name: Deleting newly created instance Task 5
     ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       instance_id: '{{ create_instance_result_5.result[0].instance_id }}'
       status: absent
     when:
        - "'failed' not in create_instance_result_5"

      
      
      
      
   
