#Ansible Module Name -- ecs_vpc.py
#Test Case : create VPC - Wait Param Validation
#Ansible Playbook created by - Abha H
---
- name: create VPC - VSwitch Param Validation
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../vars/alicloud-creds.yml
  tasks:
  # Task 1 - create VPC - Wait Param Validation with invalid value
   - block:
     - name: Scenario 1 - Create VPC - Wait Param Validation with invalid value
       ecs_vpc:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ status }}'
        cidr_block: '{{ cidrBlock }}'
        vpc_name: '{{ vpcName }}'
        description: '{{ description }}'
        vswitches: '{{ vswitch }}'
        wait: '{{ waitInvalid }}'
        wait_timeout: '{{ waitTimeout }}'
       register: create_vpc_scenario1
     - debug: var=create_vpc_scenario1
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no


   # Task 2 - create VPC - Wait Param Validation as blank
   - block:
     - name: Scenario 2 - Create VPC - Wait Param Validation as blank
       ecs_vpc:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ status }}'
        cidr_block: '{{ cidrBlock }}'
        vpc_name: '{{ vpcName }}'
        description: '{{ description }}'
        vswitches: '{{ vswitch }}'
        wait:
        wait_timeout: '{{ waitTimeout }}'
       register: create_vpc_scenario2
     - debug: var=create_vpc_scenario2
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no


   # deleting vswitch which was created in Scenario1
   - block:
     - name: Scenario 21 - Delete vswitch which created in Scenario 2
       ecs_vpc:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        vpc_id: '{{ create_vpc_scenario2.result[0]["VpcId"] }}'
        purge_vswitches: '{{ create_vpc_scenario2.result[1][0]["VSwitchId"] }}'
        state: '{{ status }}'
       register: delete_vswitch2
     - debug: var=delete_vswitch2
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - pause:
       seconds: 6

   # delete vpc which was created in Scenario1
   - block:
     - name: Scenario 22 - Delete VPC which created in Scenario 2
       ecs_vpc:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ statusAbsent }}'
        vpc_id: '{{ create_vpc_scenario2.result[0]["VpcId"] }}'
       register: delete_vpc2
     - debug: var=delete_vpc2
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no


     always:
      - assert:
         that:
            - "'failed' in create_vpc_scenario1"
            - "'Boolean sahhsj not in either boolean list' in create_vpc_scenario1.msg"

            - "'failed' not in create_vpc_scenario2"
            - "'failed' not in delete_vswitch2"
            - "'failed' not in delete_vpc2"

         msg: 'Test pass FAILED !!!'