#Ansible Module Name -- ecs_vpc.py
#Test Case : create VPC - VPC Name Param Validation
#Ansible Playbook created by - Abha H
---
- name: create VPC - VPC Name Param Validation
  hosts: localhost
  connection: local
  vars_files:
     - ../vars/test-environment.yml
     - ../vars/general-parameters.yml
     - ../../vars/alicloud-creds.yml
  tasks:
  # Task 1 - create VPC - VPC Name Param Validation with nos
   - block:
     - name: Scenario 1 - Create VPC with VPC Name Param Validation with nos
       ecs_vpc:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ status }}'
        cidr_block: '{{ cidrBlock }}'
        vpc_name: '{{ vpcNameNos }}'
        description: '{{ description }}'
        vswitches: '{{ vswitch }}'
        wait: '{{ wait }}'
        wait_timeout: '{{ waitTimeout }}'
       register: create_vpc_scenario1
     - debug: var=create_vpc_scenario1
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no


   # Task 2 - create VPC - VPC Name Param Validation with special characters
   - block:
     - name: Scenario 2 - Create VPC with VPC Name Param Validation with special characters
       ecs_vpc:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ status }}'
        cidr_block: '{{ cidrBlock }}'
        vpc_name: '{{ vpcNameSplChars }}'
        description: '{{ description }}'
        vswitches: '{{ vswitch }}'
        wait: '{{ wait }}'
        wait_timeout: '{{ waitTimeout }}'
       register: create_vpc_scenario2
     - debug: var=create_vpc_scenario2
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no


   # Task 3 - create VPC - VPC Name Param Validation with http
   - block:
     - name: Scenario 3 - Create VPC with VPC Name Param Validation with http
       ecs_vpc:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ status }}'
        cidr_block: '{{ cidrBlock }}'
        vpc_name: '{{ vpcNameWithHttp }}'
        description: '{{ description }}'
        vswitches: '{{ vswitch }}'
        wait: '{{ wait }}'
        wait_timeout: '{{ waitTimeout }}'
       register: create_vpc_scenario3
     - debug: var=create_vpc_scenario3
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no


   # Task 4 - create VPC - VPC Name Param Validation with alphanumeric values
   - block:
     - name: Scenario 4 - Create VPC with VPC Name Param Validation with alphanumeric values
       ecs_vpc:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ status }}'
        cidr_block: '{{ cidrBlock }}'
        vpc_name: '{{ vpcNameAlphaNos }}'
        description: '{{ description }}'
        vswitches: '{{ vswitch }}'
        wait: '{{ wait }}'
        wait_timeout: '{{ waitTimeout }}'
       register: create_vpc_scenario4
     - debug: var=create_vpc_scenario4
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no


   # deleting vswitch which was created in Scenario4
   - block:
     - name: Scenario 41 - Delete vswitch which created in Scenario 4
       ecs_vpc:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        vpc_id: '{{ create_vpc_scenario4.result[0]["VpcId"] }}'
        purge_vswitches: '{{ create_vpc_scenario4.result[1][0]["VSwitchId"] }}'
        state: '{{ status }}'
       register: delete_vswitch4_scenario4
     - debug: var=delete_vswitch4_scenario4
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - pause:
       seconds: 6

   # delete vpc which was created in Scenario4
   - block:
     - name: Scenario 42 - Delete VPC which created in Scenario 4
       ecs_vpc:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ statusAbsent }}'
        vpc_id: '{{ create_vpc_scenario4.result[0]["VpcId"] }}'
       register: delete_vpc4_scenario4
     - debug: var=delete_vpc4_scenario4
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - pause:
       seconds: 6


   # Task 5 - create VPC - VPC Name Param Validation with only 1 character
   - block:
     - name: Scenario 5 - Create VPC with VPC Name Param Validation with only 1 character
       ecs_vpc:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ status }}'
        cidr_block: '{{ cidrBlock }}'
        vpc_name: '{{ vpcNameWith1Char }}'
        description: '{{ description }}'
        vswitches: '{{ vswitch }}'
        wait: '{{ wait }}'
        wait_timeout: '{{ waitTimeout }}'
       register: create_vpc_scenario5
     - debug: var=create_vpc_scenario5
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no


   # Task 6 - create VPC - VPC Name Param Validation with exact 128 characters
   - block:
     - name: Scenario 6 - Create VPC with VPC Name Param Validation with exact 128 characters
       ecs_vpc:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ status }}'
        cidr_block: '{{ cidrBlock }}'
        vpc_name: '{{ vpcNameWithExact128Chars }}'
        description: '{{ description }}'
        vswitches: '{{ vswitch }}'
        wait: '{{ wait }}'
        wait_timeout: '{{ waitTimeout }}'
       register: create_vpc_scenario6
     - debug: var=create_vpc_scenario6
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no


   # deleting vswitch which was created in Scenario6
   - block:
     - name: Scenario 61 - Delete vswitch which created in Scenario 6
       ecs_vpc:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        vpc_id: '{{ create_vpc_scenario6.result[0]["VpcId"] }}'
        purge_vswitches: '{{ create_vpc_scenario6.result[1][0]["VSwitchId"] }}'
        state: '{{ status }}'
       register: delete_vswitch6_scenario6
     - debug: var=delete_vswitch6_scenario6
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - pause:
       seconds: 6

   # delete vpc which was created in Scenario6
   - block:
     - name: Scenario 62 - Delete VPC which created in Scenario 6
       ecs_vpc:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ statusAbsent }}'
        vpc_id: '{{ create_vpc_scenario6.result[0]["VpcId"] }}'
       register: delete_vpc6_scenario6
     - debug: var=delete_vpc6_scenario6
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - pause:
       seconds: 6


   # Task 7 - create VPC - VPC Name Param Validation with more than 128 characters
   - block:
     - name: Scenario 7 - Create VPC with VPC Name Param Validation with more than 128 characters
       ecs_vpc:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ status }}'
        cidr_block: '{{ cidrBlock }}'
        vpc_name: '{{ vpcNameWithMoreThan128Chars }}'
        description: '{{ description }}'
        vswitches: '{{ vswitch }}'
        wait: '{{ wait }}'
        wait_timeout: '{{ waitTimeout }}'
       register: create_vpc_scenario7
     - debug: var=create_vpc_scenario7
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no


   # Task 8 - create VPC - VPC Name Param Validation as blank
   - block:
     - name: Scenario 8 - Create VPC with VPC Name Param Validation as blank
       ecs_vpc:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ status }}'
        cidr_block: '{{ cidrBlock }}'
        vpc_name:
        description: '{{ description }}'
        vswitches: '{{ vswitch }}'
        wait: '{{ wait }}'
        wait_timeout: '{{ waitTimeout }}'
       register: create_vpc_scenario8
     - debug: var=create_vpc_scenario8
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   # deleting vswitch which was created in Scenario8
   - block:
     - name: Scenario 81 - Delete vswitch which created in Scenario 8
       ecs_vpc:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        vpc_id: '{{ create_vpc_scenario8.result[0]["VpcId"] }}'
        purge_vswitches: '{{ create_vpc_scenario8.result[1][0]["VSwitchId"] }}'
        state: '{{ status }}'
       register: delete_vswitch8_scenario8
     - debug: var=delete_vswitch8_scenario8
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - pause:
       seconds: 6

   # delete vpc which was created in Scenario6
   - block:
     - name: Scenario 82 - Delete VPC which created in Scenario 8
       ecs_vpc:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ statusAbsent }}'
        vpc_id: '{{ create_vpc_scenario8.result[0]["VpcId"] }}'
       register: delete_vpc8_scenario8
     - debug: var=delete_vpc8_scenario8
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - pause:
       seconds: 6


  # Task 9 - create VPC - vpc_name Param Validation as Vpc_name
   - block:
     - name: Scenario 9 - Create VPC with vpc_name Param Validation as Vpc_name
       ecs_vpc:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        status: '{{ status }}'
        cidr_block: '{{ cidrBlock }}'
        Vpc_name: '{{ vpcName }}'
        description: '{{ description }}'
        vswitches: '{{ vswitch }}'
        wait: '{{ wait }}'
        wait_timeout: '{{ waitTimeout }}'
       register: create_vpc_scenario9
     - debug: var=create_vpc_scenario9
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no


     always:
      - assert:
         that:
            - "'failed' in create_vpc_scenario1"
            - "'Specified VPC name is not valid.' in create_vpc_scenario1.msg[0]['Error Message']"

            - "'failed' in create_vpc_scenario2"
            - "'Specified VPC name is not valid.' in create_vpc_scenario2.msg[0]['Error Message']"

            - "'failed' in create_vpc_scenario3"
            - "'vpc_name can not start with http:// or https://' in create_vpc_scenario3.msg"

            - "'failed' not in create_vpc_scenario4"
            - "'failed' not in delete_vswitch4_scenario4"
            - "'failed' not in delete_vpc4_scenario4"

            - "'failed' in create_vpc_scenario5"
            - "'Specified VPC name is not valid' in create_vpc_scenario5.msg[0]['Error Message']"

            - "'failed' not in create_vpc_scenario6"
            - "'failed' not in delete_vswitch6_scenario6"
            - "'failed' not in delete_vpc6_scenario6"

            - "'failed' in create_vpc_scenario7"
            - "'Specified VPC name is not valid' in create_vpc_scenario7.msg[0]['Error Message']"

            - "'failed' not in create_vpc_scenario8"
            - "'failed' not in delete_vswitch8_scenario8"
            - "'failed' not in delete_vpc8_scenario8"

            - "'failed' in create_vpc_scenario9"
            - "'unsupported parameter for module: Vpc_name' in create_vpc_scenario9.msg"

         msg: 'Test pass FAILED !!!'




