#Ansible Module Name -- ecs_vpc.net.py
#Test Case : Binding Eip to an instance of different region
#Ansible Playbook created by - Abha H
---
- name: Binding Eip to an instance of different region
  hosts: localhost
  connection: local
  vars_files: 
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../vars/alicloud-creds.yml
  tasks:
  # Task 1 - Binding Eip to an instance of different region
   - block: 
     - name: Binding Eip to an instance of different region
       ecs_vpc_net: 
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ RegDiffForEIP }}'
        status: '{{ statusJoin }}'
        instance_id: '{{ instanceIdRegDiffThanEip }}'
        allocation_id: '{{ allocationId }}'
       register: result
     - debug: var=result

     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

     always:
      - assert:
         that:
            - "'failed' in result"

         msg: 'Test pass FAILED !!!'
