#!/bin/bash

MODULE_NAME=$1

date_time="$(date +%Y-%m-%d-%H-%M-%S)"

declare -A modules
modules=( ["ecs_instance_create"]="test-script/playbooks/ecs/instance/ecs_create_instance"
		  ["ecs_instance"]="test-script/ecs/instance")

info() {
  echo -e $'\r'"\n\e[1m[INFO] $@...\e[0m\n"$'\r' 2>&1 | tee -a "test-output/${date_time}.txt"
}

run_module_playbooks() {
	info "Running module ${modules[$MODULE_NAME]}"
	for f in $(find ${modules[$MODULE_NAME]} -name '*.yml')
	do
		if [[ "${f}" != */vars/* ]]
	    then
		   info "Running playbook $f"
		   ansible-playbook -i hosts $f 2>&1 | tee -a  "test-output/${date_time}.txt"
	    fi
	done
}

run_all_module_playbooks() {
   for f in $(find test-script -name '*.yml')
   do
       if [[ "${f}" != */vars/* ]]
	   then
		  info "Running playbook $f"
		  ansible-playbook -i hosts $f 2>&1 | tee -a  "test-output/${date_time}.txt"
	   fi
   done
}

if [ -z "$MODULE_NAME" ]
then
   run_all_module_playbooks
else
   run_module_playbooks
fi